// simple-cms/nuxt/app/components/forms/fields/FileUploadField.vue
<script setup lang="ts">
const { name } = defineProps<{
	modelValue: File | null;
	name: string;
}>();

const emits = defineEmits(['update:modelValue']);

const onFileChange = (e: Event) => {
	const target = e.target as HTMLInputElement;
	const file = target.files ? target.files[0] : null;
	emits('update:modelValue', file);
};
</script>

<template>
	<input :id="name" type="file" @change="onFileChange" />
</template>

// cms/sveltekit/src/lib/components/forms/fields/FileUploadField.svelte
<script lang="ts">
	import { Input } from '$lib/components/ui/input/index.js';

	interface FileUploadFieldProps {
		name: string;
		form: any;
	}

	const { name, form }: FileUploadFieldProps = $props();

	const { form: formData } = form;

	const onFileChange = (e: Event) => {
		const file = (e.target as HTMLInputElement).files?.[0];
		$formData[name] = file;
	};
</script>

<Input type="file" id={name} onchange={onFileChange} {name} />
