// cms/astro/src/components/forms/fields/SelectField.tsx
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from '@/components/ui/select';
import type { UseFormReturn } from 'react-hook-form';

interface SelectFieldProps {
  name: string;
  options: { value: string; text: string }[];
  placeholder?: string | null;
  form: UseFormReturn;
}

const SelectField = ({
  name,
  options,
  placeholder,
  form,
}: SelectFieldProps) => {
  return (
    <Select
      onValueChange={(value) => form.setValue(name, value)}
      value={form.getValues(name)}
    >
      <SelectTrigger>
        <SelectValue placeholder={placeholder || 'Select an option'} />
      </SelectTrigger>
      <SelectContent>
        {options.map((option) => (
          <SelectItem key={option.value} value={option.value}>
            {option.text}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
};

export default SelectField;

// cms/sveltekit/src/lib/components/forms/fields/SelectField.svelte
<script lang="ts">
	import * as Select from '$lib/components/ui/select/index.js';

	interface SelectFieldProps {
		name: string;
		options: { value: string; text: string }[];
		placeholder?: string | null;
		form?: any;
	}

	const { name, options, placeholder, form }: SelectFieldProps = $props();

	const formData = $derived(form.form);

	let activeLabel = $derived(
		options.find((option) => option.value === $formData[name])?.text ||
			placeholder ||
			'Select an option'
	);
</script>

<!-- onValueChange={(value) => form.setValue(name, value)} value={form.getValues(name)} -->
<Select.Root type="single" {name} bind:value={$formData[name]}>
	<Select.Trigger>
		{activeLabel}
	</Select.Trigger>
	<Select.Content class="bg-background">
		{#each options as option (option.value)}
			<Select.Item value={option.value}>
				{option.text}
			</Select.Item>
		{/each}
	</Select.Content>
</Select.Root>
