// cms/nuxt/app/components/block/Posts.vue
<script setup lang="ts">
import type { Post } from '#shared/types/schema';
import { ChevronsLeft, ChevronsRight, ChevronLeft, ChevronRight } from 'lucide-vue-next';

interface PostsProps {
	data: {
		id?: string;
		tagline?: string;
		headline?: string;
		posts: Post[];
		limit: number;
	};
}

const props = defineProps<PostsProps>();

const route = useRoute();
const router = useRouter();

const perPage = props.data.limit || 6;
const currentPage = ref(Number(route.query.page) || 1);
const visiblePages = 5;

const { data: postsData, error: _error } = await useFetch<{
	posts: Post[];
	count: number;
}>('/api/posts', {
	key: `block-posts-${props.data?.id}-${currentPage.value}`,
	query: { page: currentPage, limit: perPage },
	watch: [currentPage],
});

const posts = computed(() => postsData.value?.posts || []);
const totalPages = computed(() => Math.ceil((postsData.value?.count || 0) / perPage));

const paginationLinks = computed(() => {
	const pages: (number | string)[] = [];

	if (totalPages.value <= visiblePages) {
		for (let i = 1; i <= totalPages.value; i++) pages.push(i);
	} else {
		const rangeStart = Math.max(1, currentPage.value - 2);
		const rangeEnd = Math.min(totalPages.value, currentPage.value + 2);
		if (rangeStart > 1) pages.push('ellipsis-start');
		for (let i = rangeStart; i <= rangeEnd; i++) pages.push(i);
		if (rangeEnd < totalPages.value) pages.push('ellipsis-end');
	}

	return pages;
});

function handlePageChange(page: number) {
	if (page >= 1 && page <= totalPages.value && page !== currentPage.value) {
		currentPage.value = page;
		router.push({ query: { page } });
	}
}

import { setBlockAttr } from '~/utils/visualEditing';
</script>

<template>
	<div>
		<Tagline
			v-if="data.tagline"
			:tagline="data.tagline"
			:data-directus="
				setBlockAttr({
					blockCollection: 'block_posts',
					blockItemId: data.id,
					fields: 'tagline',
					mode: 'popover',
				})
			"
		/>
		<Headline
			v-if="data.headline"
			:headline="data.headline"
			:data-directus="setBlockAttr({ blockCollection: 'block_posts', blockItemId: data.id, fields: 'headline', mode: 'popover' })"
		/>

		<div
			class="mt-8 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6"
			:data-directus="
				setBlockAttr({
					blockCollection: 'block_posts',
					blockItemId: data.id,
					fields: ['collection', 'limit'],
					mode: 'popover',
				})
			"
		>
			<template v-if="posts?.length">
				<NuxtLink
					v-for="post in posts"
					:key="post.id"
					:to="`/blog/${post.slug}`"
					class="group block overflow-hidden rounded-lg"
				>
					<div class="relative w-full h-[256px] overflow-hidden rounded-lg">
						<DirectusImage
							v-if="post.image"
							:uuid="typeof post.image === 'string' ? post.image : post.image?.id"
							:alt="post.title"
							class="w-full h-full object-cover rounded-lg transition-transform duration-300 group-hover:scale-110"
							sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw"
						/>
					</div>
					<div class="p-4">
						<h3 class="text-xl group-hover:text-accent font-heading transition-colors duration-300">
							{{ post.title }}
						</h3>
						<p v-if="post.description" class="text-sm text-foreground mt-2">
							{{ post.description }}
						</p>
					</div>
				</NuxtLink>
			</template>
			<p v-else class="text-center text-gray-500">No posts available.</p>
		</div>
		<ClientOnly>
			<Pagination v-if="totalPages > 1 && posts?.length" class="mt-6">
				<div v-if="totalPages" class="flex items-center justify-center space-x-2">
					<div v-if="totalPages > 5 && currentPage > 1" class="flex items-center">
						<PaginationFirst @click="handlePageChange(1)">
							<ChevronsLeft class="h-4 w-4" />
						</PaginationFirst>
						<PaginationPrev @click="handlePageChange(currentPage - 1)">
							<ChevronLeft class="h-4 w-4" />
						</PaginationPrev>
					</div>
					<template v-for="(page, index) in paginationLinks" :key="index">
						<PaginationListItem v-if="typeof page === 'number'" :value="page" @click="handlePageChange(page)">
							<Button variant="outline" :class="{ 'border-none': currentPage !== page }">
								{{ page }}
							</Button>
						</PaginationListItem>
						<PaginationEllipsis v-else class="px-2" />
					</template>
					<div v-if="totalPages > 5 && currentPage < totalPages" class="flex items-center">
						<PaginationNext @click="handlePageChange(currentPage + 1)">
							<ChevronRight class="h-4 w-4" />
						</PaginationNext>
						<PaginationLast @click="handlePageChange(totalPages)">
							<ChevronsRight class="h-4 w-4" />
						</PaginationLast>
					</div>
				</div>
			</Pagination>
		</ClientOnly>
	</div>
</template>

// cms/nextjs/src/components/blocks/Posts.tsx
'use client';

import { useState, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { ChevronFirst, ChevronLast } from 'lucide-react';
import Tagline from '../ui/Tagline';
import Headline from '@/components/ui/Headline';
import DirectusImage from '@/components/shared/DirectusImage';
import Link from 'next/link';
import {
	Pagination,
	PaginationContent,
	PaginationEllipsis,
	PaginationItem,
	PaginationLink,
	PaginationNext,
	PaginationPrevious,
} from '../ui/pagination';
import { Post } from '@/types/directus-schema';
import { fetchPaginatedPosts, fetchTotalPostCount } from '@/lib/directus/fetchers';
import { setBlockAttr } from '@/lib/directus/visualEditing';

interface PostsProps {
	data: {
		id: string;
		tagline?: string;
		headline?: string;
		posts: Post[];
		limit: number;
	};
}

const Posts = ({ data }: PostsProps) => {
	const { tagline, headline, posts, limit, id } = data;
	const router = useRouter();
	const searchParams = useSearchParams();
	const visiblePages = 5;
	const initialPage = Number(searchParams.get('page')) || 1;
	const perPage = limit || 6;

	const [currentPage, setCurrentPage] = useState(initialPage);
	const [paginatedPosts, setPaginatedPosts] = useState<Post[]>(currentPage === 1 ? posts || [] : []);
	const [totalPages, setTotalPages] = useState(0);

	useEffect(() => {
		const fetchTotalPages = async () => {
			try {
				const totalCount = await fetchTotalPostCount();
				setTotalPages(Math.ceil(totalCount / perPage));
			} catch (error) {
				console.error('Error fetching total post count:', error);
			}
		};

		fetchTotalPages();
	}, [perPage]);

	useEffect(() => {
		const fetchPosts = async () => {
			try {
				if (currentPage === 1) {
					setPaginatedPosts(posts || []);

					return;
				}
				const response = await fetchPaginatedPosts(perPage, currentPage);
				setPaginatedPosts(response || []);
			} catch (error) {
				console.error('Error fetching paginated posts:', error);
				setPaginatedPosts([]);
			}
		};

		fetchPosts();
	}, [currentPage, perPage, posts]);

	const handlePageChange = (page: number) => {
		if (page >= 1 && page <= totalPages) {
			setCurrentPage(page);
			router.replace(`?page=${page}`, { scroll: false });
		}
	};

	const generatePagination = () => {
		const pages: (number | string)[] = [];
		if (totalPages <= visiblePages) {
			for (let i = 1; i <= totalPages; i++) {
				pages.push(i);
			}
		} else {
			const rangeStart = Math.max(1, currentPage - 2);
			const rangeEnd = Math.min(totalPages, currentPage + 2);
			if (rangeStart > 1) pages.push('ellipsis-start');
			for (let i = rangeStart; i <= rangeEnd; i++) pages.push(i);
			if (rangeEnd < totalPages) pages.push('ellipsis-end');
		}

		return pages;
	};

	const paginationLinks = generatePagination();

	return (
		<div>
			{tagline && (
				<Tagline
					tagline={tagline}
					data-directus={setBlockAttr({
						blockCollection: 'block_posts',
						blockItemId: id,
						fields: 'tagline',
						mode: 'popover',
					})}
				/>
			)}
			{headline && (
				<Headline
					headline={headline}
					data-directus={setBlockAttr({
						blockCollection: 'block_posts',
						blockItemId: id,
						fields: 'headline',
						mode: 'popover',
					})}
				/>
			)}

			<div
				className="mt-8 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6"
				data-directus={setBlockAttr({
					blockCollection: 'block_posts',
					blockItemId: id,
					fields: ['collection', 'limit'],
					mode: 'popover',
				})}
			>
				{paginatedPosts && paginatedPosts.length > 0 ? (
					paginatedPosts.map((post) => (
						<Link key={post.id} href={`/blog/${post.slug}`} className="group block overflow-hidden rounded-lg">
							<div className="relative w-full h-64 rounded-lg overflow-hidden">
								{post.image && (
									<DirectusImage
										uuid={typeof post.image === 'string' ? post.image : post.image?.id}
										alt={post.title}
										fill
										sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw"
										className="w-full h-auto object-cover rounded-lg transition-transform duration-300 group-hover:scale-110"
									/>
								)}
							</div>
							<div className="p-4">
								<h3 className="text-xl group-hover:text-accent font-heading transition-colors duration-300">
									{post.title}
								</h3>
								{post.description && <p className="text-sm text-foreground mt-2">{post.description}</p>}
							</div>
						</Link>
					))
				) : (
					<p className="text-center text-gray-500">No posts available.</p>
				)}
			</div>

			{totalPages > 1 && (
				<Pagination>
					<PaginationContent>
						{totalPages > visiblePages && currentPage > 1 && (
							<PaginationItem>
								<PaginationLink
									href="#"
									onClick={(e) => {
										e.preventDefault();
										handlePageChange(1);
									}}
								>
									<ChevronFirst className="size-5" />
								</PaginationLink>
							</PaginationItem>
						)}

						{totalPages > visiblePages && currentPage > 1 && (
							<PaginationItem>
								<PaginationPrevious
									href="#"
									onClick={(e) => {
										e.preventDefault();
										handlePageChange(currentPage - 1);
									}}
								/>
							</PaginationItem>
						)}

						{paginationLinks.map((page, index) =>
							typeof page === 'number' ? (
								<PaginationItem key={index}>
									<PaginationLink
										href="#"
										isActive={currentPage === page}
										onClick={(e) => {
											e.preventDefault();
											handlePageChange(page);
										}}
									>
										{page}
									</PaginationLink>
								</PaginationItem>
							) : (
								<PaginationItem key={index}>
									<PaginationEllipsis />
								</PaginationItem>
							),
						)}

						{totalPages > visiblePages && currentPage < totalPages && (
							<PaginationItem>
								<PaginationNext
									href="#"
									onClick={(e) => {
										e.preventDefault();
										handlePageChange(currentPage + 1);
									}}
								/>
							</PaginationItem>
						)}

						{totalPages > visiblePages && currentPage < totalPages && (
							<PaginationItem>
								<PaginationLink
									href="#"
									onClick={(e) => {
										e.preventDefault();
										handlePageChange(totalPages);
									}}
								>
									<ChevronLast className="size-5" />
								</PaginationLink>
							</PaginationItem>
						)}
					</PaginationContent>
				</Pagination>
			)}
		</div>
	);
};

export default Posts;
