// simple-cms/nextjs/src/components/blocks/Gallery.tsx
'use client';

import { useState } from 'react';
import DirectusImage from '@/components/shared/DirectusImage';
import Tagline from '../ui/Tagline';
import Headline from '@/components/ui/Headline';
import { Dialog, DialogContent, DialogDescription, DialogOverlay, DialogTitle } from '@/components/ui/dialog';
import { ArrowLeft, ArrowRight, ZoomIn, X } from 'lucide-react';

interface GalleryProps {
	data: {
		tagline?: string;
		headline?: string;
		items: Array<{
			id: string;
			directus_file: string;
			sort?: number;
		}>;
	};
}

const Gallery = ({ data }: GalleryProps) => {
	const { tagline, headline, items = [] } = data;
	const [isLightboxOpen, setLightboxOpen] = useState(false);
	const [currentIndex, setCurrentIndex] = useState(0);

	const sortedItems = [...items].sort((a, b) => (a.sort ?? 0) - (b.sort ?? 0));

	const isValidIndex = sortedItems.length > 0 && currentIndex >= 0 && currentIndex < sortedItems.length;

	const handleOpenLightbox = (index: number) => {
		setCurrentIndex(index);
		setLightboxOpen(true);
	};

	const handlePrev = () => {
		setCurrentIndex((prevIndex) => (prevIndex > 0 ? prevIndex - 1 : sortedItems.length - 1));
	};

	const handleNext = () => {
		setCurrentIndex((prevIndex) => (prevIndex < sortedItems.length - 1 ? prevIndex + 1 : 0));
	};

	return (
		<section className="p-6">
			{tagline && <Tagline tagline={tagline} />}
			{headline && <Headline headline={headline} />}

			{sortedItems.length > 0 && (
				<div className="mt-8 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
					{sortedItems.map((item, index) => (
						<div
							key={item.id}
							className="relative overflow-hidden rounded-lg group hover:shadow-lg transition-shadow duration-300 cursor-pointer h-[300px]"
							onClick={() => handleOpenLightbox(index)}
							aria-label={`Gallery item ${item.id}`}
						>
							<DirectusImage
								uuid={item.directus_file}
								alt={`Gallery item ${item.id}`}
								fill
								sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw"
								className="w-full h-auto object-cover rounded-lg"
							/>
							<div className="absolute inset-0 bg-white bg-opacity-60 opacity-0 group-hover:opacity-100 flex justify-center items-center transition-opacity duration-300">
								<ZoomIn className="size-10 text-gray-800" />
							</div>
						</div>
					))}
				</div>
			)}

			{/* Lightbox */}
			{isLightboxOpen && isValidIndex && (
				<Dialog open={isLightboxOpen} onOpenChange={setLightboxOpen}>
					<DialogOverlay className="fixed inset-0 bg-black bg-opacity-30 z-50" />
					<DialogContent
						className="flex bg-transparent border-none items-center justify-center p-2"
						style={{ maxHeight: '90vh' }}
					>
						<DialogTitle className="sr-only">Gallery Image</DialogTitle>
						<DialogDescription className="sr-only">
							Viewing image {currentIndex + 1} of {sortedItems.length}.
						</DialogDescription>

						<div className="relative max-w-4xl w-full">
							<DirectusImage
								uuid={sortedItems[currentIndex].directus_file}
								alt={`Gallery item ${sortedItems[currentIndex].id}`}
								width="1200"
								height="800"
								className="w-full h-auto max-h-full object-contain"
							/>
						</div>

						<button
							className="absolute -left-16 top-1/2 transform -translate-y-1/2 text-white bg-black bg-opacity-70 rounded-full p-3 hover:bg-opacity-90"
							onClick={handlePrev}
							aria-label="Previous"
						>
							<ArrowLeft className="size-8" />
						</button>
						<button
							className="absolute -right-16 top-1/2 transform -translate-y-1/2 text-white bg-black bg-opacity-70 rounded-full p-3 hover:bg-opacity-90"
							onClick={handleNext}
							aria-label="Next"
						>
							<ArrowRight className="size-8" />
						</button>
					</DialogContent>
				</Dialog>
			)}
		</section>
	);
};

export default Gallery;

// simple-cms/sveltekit/src/lib/components/blocks/Gallery.svelte
<script lang="ts">
	import DirectusImage from '../shared/DirectusImage.svelte';
	import {
		Dialog,
		DialogContent,
		DialogDescription,
		DialogOverlay,
		DialogTitle,
		Title
	} from '../ui/dialog';
	import Headline from '../ui/Headline.svelte';
	import { ArrowLeft, ArrowRight, ZoomIn, X } from 'lucide-svelte';

	interface GalleryProps {
		data: {
			title?: string;
			headline?: string;
			items: Array<{
				id: string;
				directus_file: string;
				sort?: number;
			}>;
		};
	}

	let { data }: GalleryProps = $props();
	const { title, headline, items = [] } = $derived(data);
	let isLightboxOpen = $state(false);
	let currentIndex = $state(0);

	let sortedItems = $derived([...items].sort((a, b) => (a.sort ?? 0) - (b.sort ?? 0)));
	const isValidIndex = $derived(
		sortedItems.length > 0 && currentIndex >= 0 && currentIndex < sortedItems.length
	);

	const handleOpenLightbox = (index: number) => {
		currentIndex = index;
		isLightboxOpen = true;
	};
	const handlePrev = () => {
		if (currentIndex > 0) {
			currentIndex--;
		}

		// setCurrentIndex((prevIndex) => (prevIndex > 0 ? prevIndex - 1 : sortedItems.length - 1));
	};

	const handleNext = () => {
		if (currentIndex < sortedItems.length - 1) {
			currentIndex++;
		} else {
			currentIndex = 0;
		}
		// setCurrentIndex((prevIndex) => (prevIndex < sortedItems.length - 1 ? prevIndex + 1 : 0));
	};
</script>

<section class="p-6">
	{#if title}
		<Title {title} />
	{/if}
	{#if headline}
		<Headline {headline} />
	{/if}

	{#if sortedItems.length > 0}
		<div class="mt-8 grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3">
			{#each sortedItems as item, index}
				<button
					class="group relative h-[300px] cursor-pointer overflow-hidden rounded-lg transition-shadow duration-300 hover:shadow-lg"
					onclick={() => handleOpenLightbox(index)}
					aria-label={`Gallery item ${item.id}`}
				>
					<DirectusImage
						id={item.directus_file}
						alt={`Gallery item ${item.id}`}
						fill
						sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw"
						className="w-full h-auto object-cover rounded-lg"
					/>
					<div
						class="absolute inset-0 flex items-center justify-center bg-white bg-opacity-60 opacity-0 transition-opacity duration-300 group-hover:opacity-100"
					>
						<ZoomIn className="size-10 text-gray-800" />
					</div>
				</button>
			{/each}
		</div>
	{/if}

	<!-- {/* Lightbox */} -->
	{#if isLightboxOpen && isValidIndex}
		<Dialog open={isLightboxOpen} onOpenChange={() => (isLightboxOpen = true)}>
			<DialogOverlay class="fixed inset-0 z-50 bg-black bg-opacity-30" />
			<DialogContent
				class="flex items-center justify-center border-none bg-transparent p-2"
				style={{ maxHeight: '90vh' }}
			>
				<DialogTitle class="sr-only">Gallery Image</DialogTitle>
				<DialogDescription class="sr-only">
					Viewing image {currentIndex + 1} of {sortedItems.length}.
				</DialogDescription>

				<div class="relative w-full max-w-4xl">
					<DirectusImage
						id={sortedItems[currentIndex].directus_file}
						alt={`Gallery item ${sortedItems[currentIndex].id}`}
						width="1200"
						height="800"
						className="w-full h-auto max-h-full object-contain"
					/>
				</div>

				<button
					class="absolute -left-16 top-1/2 -translate-y-1/2 transform rounded-full bg-black bg-opacity-70 p-3 text-white hover:bg-opacity-90"
					onclick={handlePrev}
					aria-label="Previous"
				>
					<ArrowLeft className="size-8" />
				</button>
				<button
					class="absolute -right-16 top-1/2 -translate-y-1/2 transform rounded-full bg-black bg-opacity-70 p-3 text-white hover:bg-opacity-90"
					onclick={handleNext}
					aria-label="Next"
				>
					<ArrowRight className="size-8" />
				</button>
			</DialogContent>
		</Dialog>
	{/if}
</section>
