// simple-cms/nextjs/src/components/blocks/Hero.tsx
import Title from '@/components/ui/Title';
import Headline from '@/components/ui/Headline';
import BaseText from '@/components/ui/Text';
import DirectusImage from '@/components/shared/DirectusImage';
import ButtonGroup from '@/components/blocks/ButtonGroup';
import { cn } from '@/lib/utils/cn';

interface HeroProps {
	data: {
		title: string;
		headline: string;
		description: string;
		alignment: 'left' | 'center' | 'right';
		image: string;
		button_group?: {
			buttons: Array<{
				id: string;
				label: string | null;
				variant: string | null;
				url: string | null;
				type: 'url' | 'page' | 'post';
				pagePermalink?: string | null;
				postSlug?: string | null;
			}>;
		};
	};
}

const Hero = ({ data }: HeroProps) => {
	const { alignment, title, headline, description, image, button_group } = data;

	return (
		<section
			className={cn(
				'relative w-full max-w-screen-lg mx-auto px-4 flex flex-col gap-6 md:gap-12 md:min-h-[60vh]',
				alignment === 'center'
					? 'items-center text-center'
					: alignment === 'right'
						? 'md:flex-row-reverse items-center'
						: 'md:flex-row items-center',
			)}
		>
			<div
				className={cn(
					'flex flex-col gap-4 w-full',
					alignment === 'center' ? 'md:w-1/2 items-center' : 'md:w-1/2 items-start',
				)}
			>
				<Title title={title} />
				<Headline headline={headline} />
				{description && <BaseText content={description} />}
				{button_group && button_group.buttons.length > 0 && (
					<div className={cn(alignment === 'center' && 'flex justify-center', 'mt-6')}>
						<ButtonGroup buttons={button_group.buttons} />
					</div>
				)}
			</div>
			{image && (
				<div className={cn('relative w-full', alignment === 'center' ? 'h-[400px]' : 'h-[562px]', 'md:w-1/2')}>
					<DirectusImage
						uuid={image}
						alt={title || 'Hero Image'}
						fill
						sizes={alignment === 'center' ? '100vw' : '(max-width: 768px) 100vw, 50vw'}
					/>
				</div>
			)}
		</section>
	);
};

export default Hero;

// simple-cms/sveltekit/src/lib/components/blocks/Hero.svelte
<script lang="ts">
	import { cn } from '$lib/utils';
	import DirectusImage from '../shared/DirectusImage.svelte';
	import BaseText from '$lib/components/ui/Text.svelte';
	import ButtonGroup from './ButtonGroup.svelte';
	import Headline from '../ui/Headline.svelte';
	import Title from '../ui/Title.svelte';
	import Tagline from '../ui/Tagline.svelte';

	interface Props {
		data: {
			title: string;
			headline: string;
			tagline: string;
			description: string;
			alignment: 'left' | 'center' | 'right';
			image: string;
			button_group?: {
				buttons: Array<{
					id: string;
					label: string | null;
					variant: string | null;
					url: string | null;
					type: 'url' | 'page' | 'post';
					pagePermalink?: string | null;
					postSlug?: string | null;
				}>;
			};
		};
	}

	let { data }: Props = $props();
	const { alignment, title, headline, description, image, button_group, tagline } = data;

	$inspect(data);
</script>

<section
	class={cn(
		'relative mx-auto flex w-full max-w-screen-lg flex-col gap-6 px-4 md:min-h-[60vh] md:gap-12',
		alignment === 'center'
			? 'items-center text-center'
			: alignment === 'right'
				? 'items-center md:flex-row-reverse'
				: 'items-center md:flex-row'
	)}
>
	<div
		class={cn(
			'flex w-full flex-col gap-4',
			alignment === 'center' ? 'items-center md:w-1/2' : 'items-start md:w-1/2'
		)}
	>
		<Tagline {tagline} />

		{#if headline}
			<Headline {headline} />
		{/if}
		{#if description}
			<BaseText content={description} />
		{/if}
		{#if button_group && button_group.buttons.length > 0}
			<div class={cn(alignment === 'center' && 'flex justify-center', 'mt-6')}>
				<ButtonGroup buttons={button_group.buttons} />
			</div>
		{/if}
	</div>
	{#if image}
		<div
			class={cn('relative w-full', alignment === 'center' ? 'h-[400px]' : 'h-[562px]', 'md:w-1/2')}
		>
			<DirectusImage
				id={image}
				alt={title || 'Hero Image'}
				fill
				sizes={alignment === 'center' ? '100vw' : '(max-width: 768px) 100vw, 50vw'}
			/>
		</div>
	{/if}
</section>

<!-- <pre>{JSON.stringify(data, null, 2)}</pre> -->
