// cms-i18n/nextjs/src/components/blocks/Hero.tsx
'use client';

import Tagline from '../ui/Tagline';
import Headline from '@/components/ui/Headline';
import BaseText from '@/components/ui/Text';
import DirectusImage from '@/components/shared/DirectusImage';
import ButtonGroup from '@/components/blocks/ButtonGroup';
import { cn } from '@/lib/utils';
import { getIsDraftPreview, setBlockAttr } from '@/lib/directus/visualEditing';

interface HeroProps {
	data: {
		id: string;
		tagline: string;
		headline: string;
		description: string;
		layout: 'image_left' | 'image_center' | 'image_right';
		image: string;
		button_group?: {
			id: string;
			buttons: Array<{
				id: string;
				label: string | null;
				variant: string | null;
				url: string | null;
				type: 'url' | 'page' | 'post';
				pagePermalink?: string | null;
				postSlug?: string | null;
			}>;
		};
	};
}

export default function Hero({ data }: HeroProps) {
	const { id, layout, tagline, headline, description, image, button_group } = data;
	const isDraftPreview = getIsDraftPreview();

	return (
		<section
			className={cn(
				'relative w-full mx-auto flex flex-col gap-6 md:gap-12',
				layout === 'image_center'
					? 'items-center text-center'
					: layout === 'image_left'
						? 'md:flex-row-reverse items-center'
						: 'md:flex-row items-center',
			)}
		>
			<div
				className={cn(
					'flex flex-col gap-4 w-full',
					layout === 'image_center' ? 'md:w-3/4 xl:w-2/3 items-center' : 'md:w-1/2 items-start',
				)}
			>
				<Tagline
					tagline={tagline}
					data-directus={setBlockAttr({
						blockCollection: 'block_hero',
						blockItemId: id,
						fields: 'tagline',
						mode: 'popover',
					})}
				/>
				<Headline
					headline={headline}
					data-directus={setBlockAttr({
						blockCollection: 'block_hero',
						blockItemId: id,
						fields: 'headline',
						mode: 'popover',
					})}
				/>
				{description && (
					<BaseText
						content={description}
						data-directus={setBlockAttr({
							blockCollection: 'block_hero',
							blockItemId: id,
							fields: 'description',
							mode: 'popover',
						})}
					/>
				)}
				{button_group && button_group.buttons.length > 0 && (
					<div
						className={cn(layout === 'image_center' && 'flex justify-center', 'mt-6')}
						data-directus={setBlockAttr(
							isDraftPreview
								? {
										blockCollection: 'block_hero',
										blockItemId: id,
										fields: 'button_group',
										mode: 'modal',
									}
								: {
										blockCollection: 'block_button_group',
										blockItemId: button_group.id,
										fields: 'buttons',
										mode: 'modal',
									},
						)}
					>
						<ButtonGroup buttons={button_group.buttons} />
					</div>
				)}
			</div>
			{image && (
				<div
					className={cn(
						'relative w-full',
						layout === 'image_center' ? 'md:w-3/4 xl:w-2/3 h-[400px]' : 'md:w-1/2 h-[562px]',
					)}
					data-directus={setBlockAttr({
						blockCollection: 'block_hero',
						blockItemId: id,
						fields: ['image', 'layout'],
						mode: 'modal',
					})}
				>
					<DirectusImage
						uuid={image}
						alt={tagline || headline || 'Hero Image'}
						fill
						sizes={layout === 'image_center' ? '100vw' : '(max-width: 768px) 100vw, 50vw'}
						className="object-contain"
					/>
				</div>
			)}
		</section>
	);
}

// cms/sveltekit/src/lib/components/blocks/Hero.svelte
<script lang="ts">
	import { cn } from '$lib/utils';
	import DirectusImage from '../shared/DirectusImage.svelte';
	import BaseText from '$lib/components/ui/Text.svelte';
	import ButtonGroup from './ButtonGroup.svelte';
	import Headline from '../ui/Headline.svelte';
	import Tagline from '../ui/Tagline.svelte';
	import { page } from '$app/state';
	import { setBlockAttr } from '$lib/directus/visualEditing';
	interface Props {
		data: {
			id: string;
			title: string;
			headline: string;
			tagline: string;
			layout: 'center' | 'left' | 'right';
			description: string;
			alignment: 'left' | 'center' | 'right';
			image: string;
			button_group?: {
				id: string;
				buttons: Array<{
					id: string;
					label: string | null;
					variant: string | null;
					url: string | null;
					type: 'url' | 'page' | 'post';
					pagePermalink?: string | null;
					postSlug?: string | null;
				}>;
			};
		};
	}

	let { data }: Props = $props();
	const { alignment, headline, description, image, button_group, tagline, layout, id } =
		$derived(data);
	const isDraftPreview = $derived(!!page.data.contentVersion);
</script>

<section
	class={cn(
		'relative mx-auto flex w-full flex-col gap-6 md:gap-12',
		layout === 'center'
			? 'items-center text-center'
			: layout === 'right'
				? 'items-center md:flex-row-reverse'
				: 'items-center md:flex-row'
	)}
>
	<div
		class={cn(
			'flex w-full flex-col gap-4',
			layout === 'center' ? 'items-center md:w-3/4 xl:w-2/3' : 'items-start md:w-1/2'
		)}
	>
		<Tagline
			{tagline}
			data-directus={setBlockAttr({
				blockCollection: 'block_hero',
				blockItemId: id,
				fields: 'tagline',
				mode: 'popover'
			})}
		/>

		{#if headline}
			<Headline
				{headline}
				data-directus={setBlockAttr({
					blockCollection: 'block_hero',
					blockItemId: id,
					fields: 'headline',
					mode: 'popover'
				})}
			/>
		{/if}
		{#if description}
			<BaseText
				content={description}
				data-directus={setBlockAttr({
					blockCollection: 'block_hero',
					blockItemId: id,
					fields: 'description',
					mode: 'popover'
				})}
			/>
		{/if}
		{#if button_group && button_group.buttons.length > 0}
			<!-- Published: edit the related button group. Draft: route via block_hero (setBlockAttr rewrites to pages). -->
			<div
				class={cn(alignment === 'center' && 'flex justify-center', 'mt-6')}
				data-directus={setBlockAttr(
					isDraftPreview
						? {
								blockCollection: 'block_hero',
								blockItemId: id,
								fields: 'button_group',
								mode: 'modal'
							}
						: {
								blockCollection: 'block_button_group',
								blockItemId: button_group.id,
								fields: 'buttons',
								mode: 'modal'
							}
				)}
			>
				<ButtonGroup buttons={button_group.buttons} />
			</div>
		{/if}
	</div>
	{#if image}
		<div
			class={cn(
				'relative w-full',
				layout === 'center' ? 'h-[400px] md:w-3/4 xl:w-2/3' : 'h-[562px] md:w-1/2'
			)}
			data-directus={setBlockAttr({
				blockCollection: 'block_hero',
				blockItemId: id,
				fields: ['image', 'layout'],
				mode: 'modal'
			})}
		>
			<DirectusImage
				uuid={image}
				alt={tagline || headline || 'Hero Image'}
				sizes={layout === 'center' ? '100vw' : '(max-width: 768px) 100vw, 50vw'}
				class="object-contain"
			/>
		</div>
	{/if}
</section>

<!-- <pre>{JSON.stringify(data, null, 2)}</pre> -->
