// cms/astro/src/components/blocks/Pricing.tsx
import Tagline from '@/components/ui/Tagline';
import Headline from '@/components/ui/Headline';
import PricingCard from '@/components/blocks/PricingCard';
import { setBlockAttr } from '@/lib/directus/visualEditing';

interface PricingCardType {
  id: string;
  title: string;
  description?: string;
  price?: string;
  badge?: string;
  features?: string[];
  button?: {
    id: string;
    label: string | null;
    variant: string | null;
    url: string | null;
  };
  is_highlighted?: boolean;
}

interface PricingData {
  id: string;
  tagline?: string;
  headline?: string;
  pricing_cards: PricingCardType[];
}

interface PricingProps {
  data: PricingData;
}

const Pricing = ({ data }: PricingProps) => {
  const { id, tagline, headline, pricing_cards } = data;

  if (!pricing_cards || !Array.isArray(pricing_cards)) {
    return null;
  }

  const gridClasses = (() => {
    if (pricing_cards.length === 1) return 'grid-cols-1';
    if (pricing_cards.length % 3 === 0) return 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3';

    return 'grid-cols-1 sm:grid-cols-2';
  })();

  return (
    <section>
      {tagline && (
        <Tagline
          tagline={tagline}
          data-directus={setBlockAttr({
            blockCollection: 'block_pricing',
            blockItemId: id,
            fields: 'tagline',
            mode: 'popover',
          })}
        />
      )}
      {headline && (
        <Headline
          headline={headline}
          data-directus={setBlockAttr({
            blockCollection: 'block_pricing',
            blockItemId: id,
            fields: 'headline',
            mode: 'popover',
          })}
        />
      )}
      <div
        className={`grid gap-6 mt-8 ${gridClasses}`}
        data-directus={setBlockAttr({
          blockCollection: 'block_pricing',
          blockItemId: id,
          fields: ['pricing_cards'],
          mode: 'modal',
        })}
      >
        {pricing_cards.map((card) => (
          <PricingCard key={card.id} card={card} />
        ))}
      </div>
    </section>
  );
};

export default Pricing;

// cms/sveltekit/src/lib/components/blocks/Pricing.svelte
<script lang="ts">
	import { setBlockAttr } from '$lib/directus/visualEditing';
	import Headline from '../ui/Headline.svelte';
	import Tagline from '../ui/Tagline.svelte';
	import PricingCard from './PricingCard.svelte';

	interface PricingCardType {
		id: string;
		title: string;
		description?: string;
		price?: string;
		badge?: string;
		features?: string[];
		button?: {
			id: string;
			label: string | null;
			variant: string | null;
			url: string | null;
		};
		is_highlighted?: boolean;
	}

	interface PricingData {
		id: string;
		tagline?: string;
		headline?: string;
		pricing_cards: PricingCardType[];
	}

	interface PricingProps {
		data: PricingData;
	}

	const { data }: PricingProps = $props();
	const { tagline, headline, pricing_cards, id } = $derived(data);

	const gridClasses = $derived.by(() => {
		if (pricing_cards.length === 1) return 'grid-cols-1';
		if (pricing_cards.length === 2) return 'grid-cols-1 sm:grid-cols-2';

		return 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3';
	});

	const containerStyles = $derived(
		pricing_cards.length <= 2 ? 'mx-auto max-w-screen-md' : 'max-w-full'
	);
</script>

{#if pricing_cards || Array.isArray(pricing_cards)}
	<section class="space-y-8">
		{#if tagline}
			<Tagline
				{tagline}
				data-directus={setBlockAttr({
					blockCollection: 'block_pricing',
					blockItemId: id,
					fields: 'tagline',
					mode: 'popover'
				})}
			/>
		{/if}
		{#if headline}
			<Headline
				{headline}
				data-directus={setBlockAttr({
					blockCollection: 'block_pricing',
					blockItemId: id,
					fields: 'headline',
					mode: 'popover'
				})}
			/>
		{/if}

		<div
			class={`grid gap-6 ${gridClasses} ${containerStyles}`}
			data-directus={setBlockAttr({
				blockCollection: 'block_pricing',
				blockItemId: id,
				fields: ['pricing_cards'],
				mode: 'modal'
			})}
		>
			{#each pricing_cards as card (card.id)}
				<PricingCard {card} />
			{/each}
		</div>
	</section>
{/if}
