// simple-cms/sveltekit/src/lib/components/layout/Footer.svelte
<script lang="ts">
	import { PUBLIC_DIRECTUS_URL } from '$env/static/public';

	import { page } from '$app/state';
	import Container from '../ui/Container.svelte';
	import LightSwitch from './LightSwitch.svelte';

	const directusURL = PUBLIC_DIRECTUS_URL;

	const globals = $derived(page.data?.globals);
	const navPrimary = $derived(page.data?.footerNavigation);
	const lightLogoUrl = $derived(
		globals?.logo ? `${directusURL}/assets/${globals.logo}` : '/images/logo.svg'
	);
	const darkLogoUrl = $derived(
		globals?.logo_dark_mode ? `${directusURL}/assets/${globals.logo_dark_mode}` : ''
	);
</script>

<footer class="bg-gray py-16 dark:bg-[var(--background-variant-color)]">
	<Container class="text-foreground dark:text-white">
		<div class="flex flex-col items-start justify-between gap-8 pt-8 md:flex-row">
			<div class="flex-1">
				<a href="/">
					{#if lightLogoUrl}
						<img
							src={lightLogoUrl}
							alt="Logo"
							class={darkLogoUrl ? 'h-auto w-[120px] dark:hidden' : 'h-auto w-[120px]'}
						/>
					{/if}
					{#if darkLogoUrl}
						<img
							src={darkLogoUrl}
							alt="Logo (Dark Mode)"
							class="hidden h-auto w-[120px] dark:block"
						/>
					{/if}
				</a>
				{#if globals?.description}
					<p class="text-description mt-2">{globals.description}</p>
				{/if}

				<!-- {/* Social Links */} -->
				{#if globals?.social_links}
					<div class="mt-4 flex space-x-4">
						{#each globals.social_links as social}
							<!-- key={social.service} -->
							<a
								href={social.url}
								target="_blank"
								rel="noopener noreferrer"
								class="hover:text-accent"
							>
								<img
									src={`/icons/social/${social.service === 'x' ? 'twitter' : social.service}.svg`}
									alt={`${social.service} icon`}
									width={24}
									height={24}
									class="size-6 dark:invert"
								/>
							</a>
						{/each}
					</div>
				{/if}
			</div>

			<div class="flex flex-1 flex-col items-start md:items-end">
				<nav class="w-full text-left md:w-auto">
					<ul class="space-y-4">
						{#if navPrimary?.items}
							{#each navPrimary.items as group (group.id)}
								<li>
									{#if group.children && group.page}
										<a href={group.page.permalink} class="text-nav font-medium hover:underline">
											{group.title}
										</a>
									{:else}
										<a href={group?.url || '#'} class="text-nav font-medium hover:underline">
											{group.title}
										</a>
									{/if}
								</li>
							{/each}
						{/if}
						<!-- <ThemeToggle className="dark:text-white" /> -->
						<li>
							<LightSwitch />
						</li>
					</ul>
				</nav>
			</div>
		</div>
	</Container>
</footer>

// simple-cms/astro/src/components/layout/Footer.tsx
"use client";
import React from "react";

import Container from "@/components/ui/Container";
import ThemeToggle from "../ui/ThemeToggle";
export default function Footer({
  navigation,
  globals,
}: {
  navigation: any;
  globals: any;
}) {
  const directusURL = import.meta.env.PUBLIC_DIRECTUS_URL;
  const lightLogoUrl = globals?.logo
    ? `${directusURL}/assets/${globals.logo}`
    : "/images/logo.svg";
  const darkLogoUrl = globals?.logo_dark_mode
    ? `${directusURL}/assets/${globals.logo_dark_mode}`
    : "";
  return (
    <footer className="bg-gray dark:bg-[var(--background-variant-color)] py-16">
      <Container className="text-foreground dark:text-white">
        <div className="flex flex-col md:flex-row justify-between items-start gap-8 pt-8">
          <div className="flex-1">
            <a
              href="/"
              className="inline-block transition-opacity hover:opacity-70"
            >
              <img
                src={lightLogoUrl}
                alt="Logo"
                className={
                  darkLogoUrl
                    ? "w-[120px] h-auto dark:hidden"
                    : "w-[120px] h-auto"
                }
              />
              {darkLogoUrl && (
                <img
                  src={darkLogoUrl}
                  alt="Logo (Dark Mode)"
                  className="w-[120px] h-auto hidden dark:block"
                />
              )}
            </a>
            {globals?.description && (
              <p className="text-description mt-2">{globals.description}</p>
            )}
            {globals?.social_links && (
              <div className="mt-4 flex space-x-4">
                {globals.social_links.map(
                  (social: { service: React.Key; url: string }) => (
                    <a
                      key={social.service}
                      href={social.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="size-8 rounded bg-transparent inline-flex items-center justify-center transition-colors hover:opacity-70"
                    >
                      <img
                        src={`/icons/social/${social.service}.svg`}
                        alt={`${social.service} icon`}
                        className="size-6 dark:invert"
                      />
                    </a>
                  )
                )}
              </div>
            )}
          </div>
          <div className="flex flex-col items-start md:items-end flex-1">
            <nav className="w-full md:w-auto text-left">
              <ul className="space-y-4">
                {navigation?.items?.map((group: any) => (
                  <li key={group.id}>
                    {group.page?.permalink ? (
                      <a
                        href={group.page.permalink}
                        className="text-nav font-medium hover:underline"
                      >
                        {group.title}
                      </a>
                    ) : (
                      <a
                        href={group.url || "#"}
                        className="text-nav font-medium hover:underline"
                      >
                        {group.title}
                      </a>
                    )}
                  </li>
                ))}
                <ThemeToggle className="dark:text-white" />
              </ul>
            </nav>
          </div>
        </div>
      </Container>
    </footer>
  );
}
