// simple-cms/nuxt/app/components/PageBuilder.vue
<script setup>
defineProps({
	sections: {
		type: Array,
		required: true,
	},
});
</script>
<template>
	<div>
		<div v-for="block in sections" :key="block.id" :class="['section', block.background, block.collection]">
			<Container>
				<BaseBlock :type="block.collection" :data="block.item" />
			</Container>
		</div>
	</div>
</template>

// simple-cms/astro/src/components/layout/PageBuilder.tsx
import type { PageBlock } from "@/types/directus-schema";

import BaseBlock from "../blocks/BaseBlock";
import React from "react";
import Container from "../ui/Container";

interface PageBuilderProps {
  sections: PageBlock[];
}
export default function PageBuilder({ sections }: PageBuilderProps) {
  const validBlocks = sections.filter(
    (block): block is PageBlock & { collection: string; item: object } =>
      typeof block.collection === "string" &&
      !!block.item &&
      typeof block.item === "object"
  );
  return (
    <div>
      {validBlocks.map((block) => (
        <div
          key={block.id}
          data-background={block.background}
          className="py-16"
        >
          <Container>
            <BaseBlock block={block} />
          </Container>
        </div>
      ))}
    </div>
  );
}
