// simple-cms/sveltekit/src/lib/components/layout/PageBuilder.svelte
<script lang="ts">
	import type { PageBlock } from '$lib/types/directus-schema';
	import BaseBlock from '../blocks/BaseBlock.svelte';
	import Container from '../ui/Container.svelte';

	interface PageBuilderProps {
		sections: PageBlock[];
	}

	let { sections }: PageBuilderProps = $props();

	const validBlocks = $derived(
		sections.filter(
			(block): block is PageBlock & { collection: string; item: object } =>
				typeof block.collection === 'string' && !!block.item && typeof block.item === 'object'
		)
	);
</script>

{#each validBlocks as block}
	<div class={`py-16`} data-background={block.background}>
		<Container>
			<BaseBlock {block} />
		</Container>
	</div>
{/each}

// simple-cms/astro/src/components/layout/PageBuilder.tsx
import type { PageBlock } from "@/types/directus-schema";

import BaseBlock from "../blocks/BaseBlock";
import React from "react";
import Container from "../ui/Container";

interface PageBuilderProps {
  sections: PageBlock[];
}
export default function PageBuilder({ sections }: PageBuilderProps) {
  const validBlocks = sections.filter(
    (block): block is PageBlock & { collection: string; item: object } =>
      typeof block.collection === "string" &&
      !!block.item &&
      typeof block.item === "object"
  );
  return (
    <div>
      {validBlocks.map((block) => (
        <div
          key={block.id}
          data-background={block.background}
          className="py-16"
        >
          <Container>
            <BaseBlock block={block} />
          </Container>
        </div>
      ))}
    </div>
  );
}
