// simple-cms/astro/src/components/layout/Footer.tsx
'use client';

import { forwardRef } from 'react';
import ThemeToggle from '@/components/ui/ThemeToggle';
import Container from '@/components/ui/Container';

interface SocialLink {
  service: string;
  url: string;
}

interface NavigationItem {
  id: string;
  title: string;
  url?: string | null;
  page?: { permalink?: string | null };
}

interface FooterProps {
  navigation: { items: NavigationItem[] };
  globals: {
    logo?: string | null;
    logo_dark_mode?: string | null;
    description?: string | null;
    social_links?: SocialLink[];
  };
}

const Footer = forwardRef<HTMLElement, FooterProps>(({ navigation, globals }, ref) => {
  const directusURL = import.meta.env.PUBLIC_DIRECTUS_URL;
  const lightLogoUrl = globals?.logo ? `${directusURL}/assets/${globals.logo}` : '/images/logo.svg';
  const darkLogoUrl = globals?.logo_dark_mode ? `${directusURL}/assets/${globals.logo_dark_mode}` : '';

  return (
    <footer ref={ref} className="bg-gray dark:bg-[var(--background-variant-color)] py-16">
      <Container className="text-foreground dark:text-white">
        <div className="flex flex-col md:flex-row justify-between items-start gap-8 pt-8">
          <div className="flex-1">
            <a href="/" className="inline-block transition-opacity hover:opacity-70">
              <img
                src={lightLogoUrl}
                alt="Logo"
                className={darkLogoUrl ? 'w-[120px] h-auto dark:hidden' : 'w-[120px] h-auto'}
              />
              {darkLogoUrl && (
                <img src={darkLogoUrl} alt="Logo (Dark Mode)" className="w-[120px] h-auto hidden dark:block" />
              )}
            </a>
            {globals?.description && <p className="text-description mt-2">{globals.description}</p>}
            {globals?.social_links && (
              <div className="mt-4 flex space-x-4">
                {globals.social_links.map((social: SocialLink) => (
                  <a
                    key={social.service}
                    href={social.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="size-8 rounded bg-transparent inline-flex items-center justify-center transition-colors hover:opacity-70"
                  >
                    <img
                      src={`/icons/social/${social.service}.svg`}
                      alt={`${social.service} icon`}
                      className="size-6 dark:invert"
                    />
                  </a>
                ))}
              </div>
            )}
          </div>
          <div className="flex flex-col items-start md:items-end flex-1">
            <nav className="w-full md:w-auto text-left">
              <ul className="space-y-4">
                {navigation?.items?.map((group: NavigationItem) => (
                  <li key={group.title}>
                    <a
                      href={group.page?.permalink || group.url || '#'}
                      className="text-nav font-medium hover:underline"
                    >
                      {group.title}
                    </a>
                  </li>
                ))}
                <ThemeToggle className="dark:text-white" />
              </ul>
            </nav>
          </div>
        </div>
      </Container>
    </footer>
  );
});

Footer.displayName = 'Footer';
export default Footer;

// simple-cms/nuxt/app/components/Footer.vue
<script setup lang="ts">
import { computed } from 'vue';

// Define the structure of social links and navigation items
export interface SocialLink {
	service: string;
	url: string;
}

export interface NavigationItem {
	id: string;
	title: string;
	url?: string | null;
	page?: {
		permalink?: string | null;
	};
}

// Define props interface for the Footer
export interface FooterProps {
	navigation: {
		items: NavigationItem[];
	};
	globals: {
		logo?: string | null;
		logo_dark_mode?: string | null;
		description?: string | null;
		social_links?: SocialLink[];
	};
}

// Use defineProps with defaults to provide default values
const props = defineProps<FooterProps>();

// Get runtime configuration
const runtimeConfig = useRuntimeConfig();

// Compute the URLs for the light and dark logos
const lightLogoUrl = computed(() =>
	props.globals.logo ? `${runtimeConfig.public.directusUrl}/assets/${props.globals.logo}` : '/images/logo.svg',
);

const darkLogoUrl = computed(() =>
	props.globals.logo_dark_mode ? `${runtimeConfig.public.directusUrl}/assets/${props.globals.logo_dark_mode}` : '',
);
</script>

<template>
	<footer v-if="globals" class="bg-gray dark:bg-[var(--background-variant-color)] py-16">
		<Container class="text-foreground dark:text-white">
			<div class="flex flex-col md:flex-row justify-between items-start gap-8 pt-8">
				<!-- Logo and Description -->
				<div class="flex-1">
					<NuxtLink to="/" class="inline-block transition-opacity hover:opacity-70">
						<img
							v-if="lightLogoUrl"
							:src="lightLogoUrl"
							alt="Logo"
							:class="['w-[120px] h-auto', darkLogoUrl ? 'dark:hidden' : '']"
						/>
						<img
							v-if="darkLogoUrl"
							:src="darkLogoUrl"
							alt="Logo (Dark Mode)"
							class="w-[120px] h-auto hidden dark:block"
						/>
					</NuxtLink>

					<p v-if="props.globals.description" class="text-description mt-2">
						{{ props.globals.description }}
					</p>

					<!-- Social Links -->
					<div v-if="props.globals.social_links?.length" class="mt-4 flex space-x-4">
						<a
							v-for="social in props.globals.social_links"
							:key="social.service"
							:href="social.url"
							target="_blank"
							rel="noopener noreferrer"
							class="size-8 rounded bg-transparent inline-flex items-center justify-center transition-colors hover:opacity-70"
						>
							<img
								:src="`/icons/social/${social.service}.svg`"
								:alt="`${social.service} icon`"
								class="size-6 dark:invert"
							/>
						</a>
					</div>
				</div>

				<!-- Navigation Links -->
				<div class="flex flex-col items-start md:items-end flex-1">
					<nav v-if="props.navigation.items?.length" class="w-full md:w-auto text-left">
						<ul class="space-y-4">
							<li v-for="item in props.navigation.items" :key="item.id">
								<NuxtLink
									v-if="item.page?.permalink"
									:to="item.page.permalink"
									class="text-nav font-medium hover:underline"
								>
									{{ item.title }}
								</NuxtLink>
								<a v-else :href="item.url || '#'" class="text-nav font-medium hover:underline">
									{{ item.title }}
								</a>
							</li>
						</ul>
						<ThemeToggle class="dark:text-white mt-4" />
					</nav>
				</div>
			</div>
		</Container>
	</footer>
</template>
