// simple-cms/nuxt/app/components/shared/DirectusImage.vue
<script setup lang="ts">
import { getDirectusAssetURL } from '@@/server/utils/directus-utils';

interface DirectusImageProps {
	uuid: string;
	alt: string;
	width?: number;
	height?: number;
	[key: string]: any;
}

const props = withDefaults(defineProps<DirectusImageProps>(), {
	width: undefined,
	height: undefined,
});

const { uuid, alt, width, height, ...rest } = props;

const src = computed(() => getDirectusAssetURL(uuid));
</script>

<template>
	<img :src="src" :alt="alt" :width="width" :height="height" v-bind="rest" />
</template>

// simple-cms/sveltekit/src/lib/components/shared/DirectusImage.svelte
<script lang="ts">
	import { getDirectusAssetURL } from '$lib/directus/directus-utils';
	import { type DirectusFile } from '$lib/types/directus-schema';

	interface Props {
		id: string | DirectusFile;
		width?: number | string;
		height?: number | string;
		alt: string;
		className?: string;
		[key: string]: any;
	}

	let { id, width, height, alt, className, ...props }: Props = $props();
	let src = $derived(getDirectusAssetURL(id));
</script>

<!-- {width}
{height} -->
<img {src} {alt} {width} {height} class={className} />
