// cms/astro/src/components/ui/Tagline.tsx
import React from 'react';

interface TitleProps {
  tagline?: string | null;
  className?: string;
  as?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'span' | 'div';
  'data-directus'?: string;
}

const Tagline = ({
  tagline,
  className = '',
  as: Component = 'h2',
  'data-directus': dataDirectus,
}: TitleProps) => {
  if (!tagline) return null;

  return (
    <Component
      className={`font-heading text-accent font-normal uppercase ${className}
         text-lg md:text-xl lg:text-tagline`}
      data-directus={dataDirectus}
    >
      {tagline}
    </Component>
  );
};

export default Tagline;

// simple-cms/sveltekit/src/lib/components/ui/Tagline.svelte
<script lang="ts">
	interface TitleProps {
		tagline?: string | null;
		class?: string;
		as?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'span' | 'div';
	}

	const { tagline, class: className = '', as = 'p' }: TitleProps = $props();
</script>

{#if tagline}
	<svelte:element
		this={as}
		class={`font-heading text-lg font-normal uppercase text-accent md:text-xl lg:text-tagline ${className}`}
	>
		{tagline}
	</svelte:element>
{/if}
