// cms/sveltekit/src/lib/components/blocks/Gallery.svelte
<script lang="ts">
	import DirectusImage from '../shared/DirectusImage.svelte';
	import {
		Dialog,
		DialogClose,
		DialogContent,
		DialogDescription,
		DialogOverlay,
		DialogTitle
	} from '../ui/dialog';

	import { ArrowLeft, ArrowRight, ZoomIn, X } from '@lucide/svelte';
	import Headline from '../ui/Headline.svelte';
	import Tagline from '../ui/Tagline.svelte';
	import { setBlockAttr } from '$lib/directus/visualEditing';

	interface GalleryProps {
		data: {
			id: string;
			tagline?: string;
			headline?: string;
			items: Array<{
				id: string;
				directus_file: string;
				sort?: number;
			}>;
		};
	}

	let { data }: GalleryProps = $props();
	const { tagline, headline, items = [], id } = $derived(data);
	let isLightboxOpen = $state(false);
	let currentIndex = $state(0);

	let sortedItems = $derived(items ? [...items].sort((a, b) => (a.sort ?? 0) - (b.sort ?? 0)) : []);
	const isValidIndex = $derived(
		sortedItems.length > 0 && currentIndex >= 0 && currentIndex < sortedItems.length
	);

	const handleOpenLightbox = (index: number) => {
		currentIndex = index;
		isLightboxOpen = true;
	};
	const handlePrev = () => {
		if (currentIndex > 0) {
			currentIndex--;
		}

		// setCurrentIndex((prevIndex) => (prevIndex > 0 ? prevIndex - 1 : sortedItems.length - 1));
	};

	const handleNext = () => {
		if (currentIndex < sortedItems.length - 1) {
			currentIndex++;
		} else {
			currentIndex = 0;
		}
		// setCurrentIndex((prevIndex) => (prevIndex < sortedItems.length - 1 ? prevIndex + 1 : 0));
	};
</script>

<section class="p-6">
	{#if tagline}
		<Tagline
			{tagline}
			data-directus={setBlockAttr({
				blockCollection: 'block_gallery',
				blockItemId: id,
				fields: 'tagline',
				mode: 'popover'
			})}
		/>
	{/if}
	{#if headline}
		<Headline
			{headline}
			data-directus={setBlockAttr({
				blockCollection: 'block_gallery',
				blockItemId: id,
				fields: 'headline',
				mode: 'popover'
			})}
		/>
	{/if}

	{#if sortedItems.length > 0}
		<div
			class="mt-8 grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3"
			data-directus={setBlockAttr({
				blockCollection: 'block_gallery',
				blockItemId: id,
				fields: 'items',
				mode: 'modal'
			})}
		>
			{#each sortedItems as item, index (item.id)}
				<button
					class="group relative h-[300px] overflow-hidden rounded-lg transition-shadow duration-300 hover:shadow-lg"
					onclick={() => handleOpenLightbox(index)}
					aria-label={`Gallery item ${item.id}`}
				>
					<DirectusImage
						uuid={item.directus_file}
						alt={`Gallery item ${item.id}`}
						fill
						sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw"
						class="h-auto w-full rounded-lg object-cover"
					/>
					<div
						class="absolute inset-0 flex items-center justify-center bg-white bg-opacity-60 opacity-0 transition-opacity duration-300 group-hover:opacity-100"
					>
						<ZoomIn class="size-10 text-gray-800" />
					</div>
				</button>
			{/each}
		</div>
	{/if}

	<!-- {/* Lightbox */} -->
	{#if isLightboxOpen && isValidIndex}
		<Dialog open={isLightboxOpen} onOpenChange={() => (isLightboxOpen = false)}>
			<DialogOverlay class="fixed inset-0 z-50 bg-black bg-opacity-30" />
			<DialogContent
				class="z-50 flex max-h-full max-w-full items-center  justify-center border-none bg-transparent p-2"
			>
				<DialogTitle class="sr-only">Gallery Image</DialogTitle>
				<DialogDescription class="sr-only">
					Viewing image {currentIndex + 1} of {sortedItems.length}.
				</DialogDescription>

				<div class="relative flex h-[90vh] w-[90vw] items-center justify-center">
					<DirectusImage
						uuid={sortedItems[currentIndex].directus_file}
						alt={`Gallery item ${sortedItems[currentIndex].id}`}
						width={1200}
						height={800}
						class="h-auto max-h-full w-full object-contain"
					/>
				</div>

				<div class="absolute inset-x-0 bottom-4 flex items-center justify-between px-4">
					<button
						class="flex items-center gap-2 rounded-full bg-black bg-opacity-70 px-4 py-2 text-white hover:bg-opacity-90"
						onclick={handlePrev}
						aria-label="Previous"
					>
						<ArrowLeft class="size-8" />
						<span>Prev</span>
					</button>
					<button
						class="flex items-center gap-2 rounded-full bg-black bg-opacity-70 px-4 py-2 text-white hover:bg-opacity-90"
						onclick={handleNext}
						aria-label="Next"
					>
						<span>Next</span>
						<ArrowRight class="size-8" />
					</button>
				</div>
				<DialogClose>
					<button
						class="absolute right-4 top-4 rounded-full bg-black bg-opacity-70 p-2 text-white hover:bg-opacity-90"
						aria-label="Close"
					>
						<X class="size-8" />
					</button>
				</DialogClose>
			</DialogContent>
		</Dialog>
	{/if}
</section>

// cms/astro/src/components/blocks/Gallery.tsx
import { useEffect, useState } from 'react';
import DirectusImage from '@/components/shared/DirectusImage';
import Tagline from '@/components/ui/Tagline';
import Headline from '@/components/ui/Headline';
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogClose } from '@/components/ui/dialog';
import { ArrowLeft, ArrowRight, ZoomIn, X } from 'lucide-react';
import { setBlockAttr } from '@/lib/directus/visualEditing';

interface GalleryItem {
  id: string;
  directus_file: string;
  sort?: number;
}

interface GalleryData {
  id: string;
  tagline?: string;
  headline?: string;
  items?: GalleryItem[];
}

interface GalleryProps {
  data: GalleryData;
}

const Gallery = ({ data }: GalleryProps) => {
  const { tagline, headline, items, id } = data;

  const [isLightboxOpen, setLightboxOpen] = useState(false);
  const [currentIndex, setCurrentIndex] = useState(0);

  const sortedItems = items ? [...items].sort((a, b) => (a.sort ?? 0) - (b.sort ?? 0)) : [];
  const isValidIndex = sortedItems.length > 0 && currentIndex >= 0 && currentIndex < sortedItems.length;

  const handleOpenLightbox = (index: number) => {
    setCurrentIndex(index);
    setLightboxOpen(true);
  };

  const handlePrev = () => {
    setCurrentIndex((prev) => (prev > 0 ? prev - 1 : sortedItems.length - 1));
  };

  const handleNext = () => {
    setCurrentIndex((prev) => (prev < sortedItems.length - 1 ? prev + 1 : 0));
  };

  const handleKeyDown = (e: KeyboardEvent) => {
    if (isLightboxOpen) {
      e.stopPropagation();

      switch (e.key) {
        case 'ArrowLeft':
          e.preventDefault();
          handlePrev();
          break;
        case 'ArrowRight':
          e.preventDefault();
          handleNext();
          break;
        case 'Escape':
          e.preventDefault();
          setLightboxOpen(false);
          break;
        default:
          break;
      }
    }
  };

  useEffect(() => {
    window.addEventListener('keydown', handleKeyDown);

    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isLightboxOpen]);

  return (
    <section className="relative">
      {tagline && (
        <Tagline
          tagline={tagline}
          data-directus={setBlockAttr({
            blockCollection: 'block_gallery',
            blockItemId: id,
            fields: 'tagline',
            mode: 'popover',
          })}
        />
      )}
      {headline && (
        <Headline
          headline={headline}
          data-directus={setBlockAttr({
            blockCollection: 'block_gallery',
            blockItemId: id,
            fields: 'headline',
            mode: 'popover',
          })}
        />
      )}

      {sortedItems.length > 0 && (
        <div
          className="mt-8 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6"
          data-directus={setBlockAttr({
            blockCollection: 'block_gallery',
            blockItemId: id,
            fields: 'items',
            mode: 'modal',
          })}
        >
          {sortedItems.map((item, index) => (
            <div
              key={item.id}
              className="relative overflow-hidden rounded-lg group hover:shadow-lg transition-shadow duration-300 cursor-pointer h-[300px]"
              onClick={() => handleOpenLightbox(index)}
              aria-label={`Gallery item ${item.id}`}
            >
              {item.directus_file ? (
                <DirectusImage
                  uuid={item.directus_file}
                  alt={`Gallery item ${item.id}`}
                  fill
                  sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw"
                  className="w-full h-auto object-cover rounded-lg"
                />
              ) : (
                <div className="flex items-center justify-center h-full text-sm text-gray-500">Image not available</div>
              )}
              <div className="absolute inset-0 bg-white bg-opacity-60 opacity-0 group-hover:opacity-100 flex justify-center items-center transition-opacity duration-300">
                <ZoomIn className="size-10 text-gray-800" />
              </div>
            </div>
          ))}
        </div>
      )}

      {isLightboxOpen && isValidIndex && (
        <Dialog open={isLightboxOpen} onOpenChange={setLightboxOpen}>
          <DialogContent
            className="flex max-w-full max-h-full items-center justify-center p-2 bg-transparent border-none z-50"
            hideCloseButton
          >
            <DialogTitle className="sr-only">Gallery Image</DialogTitle>
            <DialogDescription className="sr-only">
              Viewing image {currentIndex + 1} of {sortedItems.length}.
            </DialogDescription>

            <div className="relative flex justify-center items-center w-[90vw] h-[90vh]">
              <DirectusImage
                uuid={sortedItems[currentIndex].directus_file}
                alt={`Gallery item ${sortedItems[currentIndex].id}`}
                width={1200}
                height={800}
                className="size-full object-contain"
              />
            </div>
            <div className="absolute bottom-4 inset-x-0 flex justify-between items-center px-4">
              <button
                type="button"
                className="flex items-center gap-2 text-white bg-black bg-opacity-70 rounded-full px-4 py-2 hover:bg-opacity-90"
                onClick={handlePrev}
                aria-label="Previous"
              >
                <ArrowLeft className="size-8" />
                <span>Prev</span>
              </button>
              <button
                type="button"
                className="flex items-center gap-2 text-white bg-black bg-opacity-70 rounded-full px-4 py-2 hover:bg-opacity-90"
                onClick={handleNext}
                aria-label="Next"
              >
                <span>Next</span>
                <ArrowRight className="size-8" />
              </button>
            </div>
            <DialogClose asChild>
              <button
                type="button"
                className="absolute top-4 right-4 text-white bg-black bg-opacity-70 rounded-full p-2 hover:bg-opacity-90"
                aria-label="Close"
              >
                <X className="size-8" />
              </button>
            </DialogClose>
          </DialogContent>
        </Dialog>
      )}
    </section>
  );
};

export default Gallery;
