// cms/sveltekit/src/routes/[...permalink]/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import PageBuilder from '$lib/components/layout/PageBuilder.svelte';
	import type { PageBlock } from '$lib/types/directus-schema.js';
	import { Button } from '$lib/components/ui/button';
	import { Pencil } from '@lucide/svelte';
	import { setAttr } from '$lib/directus/visualEditing';

	let { data } = $props();

	const blocks: PageBlock[] = $derived.by(() => {
		if (!data.blocks) return [];
		return data.blocks.filter(
			(block: any): block is PageBlock => typeof block === 'object' && block.collection
		);
	});
</script>

<svelte:head>
	<title>{data.title || ''}</title>
	<meta name="description" content={data.seo?.meta_description || ''} />
</svelte:head>

<div class="relative">
	<PageBuilder sections={blocks} />
	{#if page.data.visualEditingEnabled && data.id}
		<div class="fixed inset-x-0 bottom-4 z-[60] flex w-full items-center justify-center gap-2 p-4">
			<!-- If you're not using the visual editor it's safe to remove this element. Just a helper to let editors add edit / add new blocks to a page. -->
			<Button
				id="visual-editing-button"
				variant="secondary"
				class="visual-editing-button-class"
				data-directus={setAttr({
					collection: 'pages',
					item: data.id,
					fields: ['blocks', 'meta_m2a_button'],
					mode: 'modal'
				})}
			>
				<Pencil class="mr-2 size-4" />
				Edit All Blocks
			</Button>
		</div>
	{/if}
</div>

<style>
	/* Safe to remove this if you're not using the visual editor. */
	:global(
		.directus-visual-editing-overlay.visual-editing-button-class
			.directus-visual-editing-edit-button
	) {
		position: absolute;
		inset: 0;
		width: 100%;
		height: 100%;
		transform: none;
		background: transparent;
	}
	/* Hide the rectangle around the "Edit All Blocks" button (customClass set by second apply() in layout) */
	:global(.directus-visual-editing-overlay.visual-editing-button-class) {
		display: none !important;
	}
	/* Ensure Visual Editor rectangles appear below header and buttons */
	:global(.directus-visual-editing-overlay) {
		z-index: 40 !important;
	}
</style>

// cms/nuxt/app/pages/[...permalink].vue
<script setup lang="ts">
import type { Page, PageBlock } from '#shared/types/schema';
import { withLeadingSlash, withoutTrailingSlash } from 'ufo';
import { firstQueryValue, isPreviewQueryValue, normalizeVersionQuery } from '~/utils/preview-query';

const route = useRoute();
const { enabled } = useLivePreview();
const previewActive = computed(() => isPreviewQueryValue(route.query.preview) || enabled.value);
const pageUrl = useRequestURL();
const { isVisualEditingEnabled, apply, setAttr } = useVisualEditing();

const permalink = withoutTrailingSlash(withLeadingSlash(route.path));

const {
	data: page,
	error,
	refresh,
} = await useFetch<Page>('/api/pages/one', {
	key: computed(() => `pages-${permalink}-${normalizeVersionQuery(route.query.version) ?? ''}-${firstQueryValue(route.query.id) ?? ''}-${previewActive.value ? 'p' : '0'}`),
	query: computed(() => ({
		permalink,
		preview: previewActive.value ? true : undefined,
		id: firstQueryValue(route.query.id),
		version: normalizeVersionQuery(route.query.version),
	})),
});

if (!page.value || error.value) {
	throw createError({ statusCode: 404, statusMessage: 'Page not found', fatal: true });
}

const pageBlocks = computed(() => (page.value?.blocks as PageBlock[]) || []);

useSeoMeta({
	title: page.value?.seo?.title || page.value?.title || '',
	description: page.value?.seo?.meta_description || '',
	ogTitle: page.value?.seo?.title || page.value?.title || '',
	ogDescription: page.value?.seo?.meta_description || '',
	ogUrl: pageUrl.toString(),
});

// Helper functions for Visual Editing
function applyVisualEditing() {
	apply({
		onSaved: async () => {
			await refresh();
		},
	});
}

function applyVisualEditingButton() {
	apply({
		elements: document.querySelector('#visual-editing-button') as HTMLElement,
		customClass: 'visual-editing-button-class',
		onSaved: async () => {
			await refresh();
			// This makes sure the visual editor elements are updated after the page is refreshed. In case you've added new blocks to the page.
			await nextTick();
			applyVisualEditing();
		},
	});
}

onMounted(() => {
	if (!isVisualEditingEnabled.value) return;
	applyVisualEditingButton();
	applyVisualEditing();
});
</script>

<template>
	<div class="relative">
		<PageBuilder v-if="pageBlocks" :sections="pageBlocks" />
		<div
			v-if="isVisualEditingEnabled && page"
			class="fixed z-[60] w-full bottom-4 left-0 right-0 p-4 flex justify-center items-center gap-2"
		>
			<!-- If you're not using the visual editor it's safe to remove this element. Just a helper to let editors add edit / add new blocks to a page. -->
			<Button
				id="visual-editing-button"
				variant="secondary"
				:data-directus="
					setAttr({ collection: 'pages', item: page.id, fields: ['blocks', 'meta_m2a_button'], mode: 'modal' })
				"
			>
				<Icon name="lucide:pencil" />
				Edit All Blocks
			</Button>
		</div>
	</div>
</template>

<style>
.directus-visual-editing-overlay.visual-editing-button-class .directus-visual-editing-edit-button {
	/* Not using style scoped because the visual editor adds it's own elements to the page. Safe to remove this if you're not using the visual editor. */
	position: absolute;
	inset: 0;
	width: 100%;
	height: 100%;
	transform: none;
	background: transparent;
}
/* Hide the rectangle but keep the overlay above the button so it can receive clicks */
.directus-visual-editing-overlay.visual-editing-button-class {
	opacity: 0 !important;
	z-index: 70 !important;
}
/* Ensure Visual Editor rectangles appear below header and buttons */
.directus-visual-editing-overlay {
	z-index: 40 !important;
}
</style>
