// simple-cms/nuxt/app/pages/[...permalink].vue
<script setup lang="ts">
import type { Page, PageBlock } from '#shared/types/schema';
import { withLeadingSlash, withoutTrailingSlash } from 'ufo';

const route = useRoute();
const { enabled, state } = useLivePreview();
const pageUrl = useRequestURL();
const { isVisualEditingEnabled, apply, setAttr } = useVisualEditing();

const permalink = withoutTrailingSlash(withLeadingSlash(route.path));

const pageBuilder = useTemplateRef<HTMLElement>('page-builder');

const {
	data: page,
	error,
	refresh,
} = await useFetch<Page>('/api/pages/one', {
	key: `pages-${permalink}`,
	query: {
		permalink,
		preview: enabled.value ? true : undefined,
		token: enabled.value ? state.token : undefined,
	},
});

if (!page.value || error.value) {
	throw createError({ statusCode: 404, statusMessage: 'Page not found', fatal: true });
}

const pageBlocks = computed(() => (page.value?.blocks as PageBlock[]) || []);

useSeoMeta({
	title: page.value?.seo?.title || page.value?.title || '',
	description: page.value?.seo?.meta_description || '',
	ogTitle: page.value?.seo?.title || page.value?.title || '',
	ogDescription: page.value?.seo?.meta_description || '',
	ogUrl: pageUrl.toString(),
});

function applyPageBuilder() {
	apply({
		elements: pageBuilder.value as HTMLElement,
		onSaved: () => {
			refresh().then(() => {
				// This makes sure the visual editor elements are updated after the page is refreshed. In case you've added new blocks to the page.
				nextTick(() => {
					apply({
						elements: pageBuilder.value as HTMLElement,
					});
				});
			});
		},
	});
}

onMounted(() => {
	if (!isVisualEditingEnabled.value) return;
	applyPageBuilder();
});
</script>

<template>
	<div ref="page-builder">
		<PageBuilder v-if="pageBlocks" :sections="pageBlocks" />
		<div
			v-if="isVisualEditingEnabled && page"
			class="sticky bottom-0 left-0 right-0 p-4 flex justify-center items-center gap-2"
		>
			<!-- If you're not using the visual editor it's safe to remove this element. Just a helper to let editors add new blocks to a page. -->
			<Button
				variant="secondary"
				class="visual-editing-rect"
				:data-directus="
					setAttr({ collection: 'pages', item: page.id, fields: ['blocks', 'meta_m2a_button'], mode: 'modal' })
				"
			>
				Edit All Blocks
			</Button>
		</div>
	</div>
</template>

// cms/sveltekit/src/routes/[...permalink]/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import PageBuilder from '$lib/components/layout/PageBuilder.svelte';
	import type { PageBlock } from '$lib/types/directus-schema.js';
	import { Button } from '$lib/components/ui/button';
	import { Pencil } from '@lucide/svelte';
	import { setAttr } from '$lib/directus/visualEditing';

	let { data } = $props();

	const blocks: PageBlock[] = $derived.by(() => {
		if (!data.blocks) return [];
		return data.blocks.filter(
			(block: any): block is PageBlock => typeof block === 'object' && block.collection
		);
	});
</script>

<svelte:head>
	<title>{data.title || ''}</title>
	<meta name="description" content={data.description || ''} />
</svelte:head>

<div class="relative">
	<PageBuilder sections={blocks} />
	{#if page.data.visualEditingEnabled && data.id}
		<div class="fixed inset-x-0 bottom-4 z-50 flex w-full items-center justify-center gap-2 p-4">
			<!-- If you're not using the visual editor it's safe to remove this element. Just a helper to let editors add edit / add new blocks to a page. -->
			<Button
				id="visual-editing-button"
				variant="secondary"
				class="visual-editing-button-class"
				data-directus={setAttr({
					collection: 'pages',
					item: data.id,
					fields: ['blocks', 'meta_m2a_button'],
					mode: 'modal'
				})}
			>
				<Pencil class="mr-2 size-4" />
				Edit All Blocks
			</Button>
		</div>
	{/if}
</div>

<style>
	/* Safe to remove this if you're not using the visual editor. */
	:global(
		.directus-visual-editing-overlay.visual-editing-button-class
			.directus-visual-editing-edit-button
	) {
		position: absolute;
		inset: 0;
		width: 100%;
		height: 100%;
		transform: none;
		background: transparent;
	}
</style>
