// simple-cms/astro/src/components/blocks/RichText.tsx
import React from 'react';
import Tagline from '@/components/ui/Tagline';
import Headline from '@/components/ui/Headline';
import Text from '@/components/ui/Text';
import { setAttr } from '@directus/visual-editing';

interface RichTextProps {
  data: {
    id: string;
    tagline?: string;
    headline?: string;
    content?: string;
    alignment?: 'left' | 'center' | 'right';
  };
  className?: string;
}

const RichText = ({ data, className }: RichTextProps) => {
  const { id, tagline, headline, content, alignment = 'left' } = data;

  return (
    <div className={`mx-auto max-w-[600px] space-y-6 text-${alignment} ${className}`}>
      {tagline && (
        <Tagline
          tagline={tagline}
          data-directus={setAttr({
            collection: 'block_richtext',
            item: id,
            fields: 'tagline',
            mode: 'popover',
          })}
        />
      )}
      {headline && (
        <Headline
          headline={headline}
          data-directus={setAttr({
            collection: 'block_richtext',
            item: id,
            fields: 'headline',
            mode: 'popover',
          })}
        />
      )}
      {content && (
        <Text
          content={content}
          data-directus={setAttr({
            collection: 'block_richtext',
            item: id,
            fields: 'content',
            mode: 'popover',
          })}
        />
      )}
    </div>
  );
};

export default RichText;

// simple-cms/nuxt/app/components/block/RichText.vue
<script setup lang="ts">
import { setAttr } from '@directus/visual-editing';
import Text from '~/components/base/Text.vue';

interface RichTextProps {
	data: {
		id?: string;
		tagline?: string;
		headline?: string;
		content?: string;
		alignment?: 'left' | 'center' | 'right';
		className?: string;
	};
}

const props = withDefaults(defineProps<RichTextProps>(), {
	data: () => ({
		alignment: 'left',
	}),
});

const { id, tagline, headline, content, alignment, className } = props.data;
</script>

<template>
	<div
		:class="[
			'mx-auto max-w-[600px] space-y-6',
			{
				'text-center': alignment === 'center',
				'text-right': alignment === 'right',
				'text-left': alignment === 'left',
			},
			className,
		]"
	>
		<Tagline
			v-if="tagline"
			:tagline="tagline"
			v-bind="
				id
					? { 'data-directus': setAttr({ collection: 'block_richtext', item: id, fields: 'tagline', mode: 'popover' }) }
					: {}
			"
		/>
		<Headline
			v-if="headline"
			:headline="headline"
			v-bind="
				id
					? {
							'data-directus': setAttr({ collection: 'block_richtext', item: id, fields: 'headline', mode: 'popover' }),
						}
					: {}
			"
		/>
		<Text
			v-if="content"
			:content="content"
			v-bind="
				id
					? { 'data-directus': setAttr({ collection: 'block_richtext', item: id, fields: 'content', mode: 'popover' }) }
					: {}
			"
		/>
	</div>
</template>
