// simple-cms/nuxt/app/components/block/Hero.vue
<script setup lang="ts">
import Text from '~/components/base/Text.vue';
import DirectusImage from '~/components/shared/DirectusImage.vue';
import { setAttr } from '@directus/visual-editing';

interface HeroProps {
	data: {
		id: string;
		tagline: string;
		headline: string;
		description: string;
		layout: 'image_image_left' | 'image_center' | 'image_left';
		image: string;
		button_group?: {
			buttons: Array<{
				id: string;
				label: string | null;
				variant: string | null;
				url: string | null;
				type: 'url' | 'page' | 'post';
				pagePermalink?: string | null;
				postSlug?: string | null;
			}>;
		};
	};
}

const props = defineProps<HeroProps>();
const { id, tagline, headline, description, layout, image, button_group } = props.data;
</script>

<template>
	<section
		class="relative w-full mx-auto flex flex-col gap-6 md:gap-12"
		:class="{
			'items-center text-center': layout === 'image_center',
			'md:flex-row-reverse items-center': layout === 'image_left',
			'md:flex-row items-center': layout !== 'image_center' && layout !== 'image_left',
		}"
		:data-directus="
			setAttr({
				collection: 'block_hero',
				item: id,
				fields: ['layout', 'image', 'tagline', 'headline', 'description', 'button_group'],
			})
		"
	>
		<div
			class="flex flex-col gap-4 w-full"
			:class="{
				'md:w-3/4 xl:w-2/3 items-center': layout === 'image_center',
				'md:w-1/2 items-start': layout !== 'image_center',
			}"
		>
			<Tagline
				:tagline="tagline"
				:data-directus="setAttr({ collection: 'block_hero', item: id, fields: 'tagline', mode: 'popover' })"
			/>
			<Headline
				:headline="headline"
				:data-directus="setAttr({ collection: 'block_hero', item: id, fields: 'headline', mode: 'popover' })"
			/>
			<Text
				v-if="description"
				:content="description"
				:data-directus="setAttr({ collection: 'block_hero', item: id, fields: 'description', mode: 'popover' })"
			/>

			<div
				v-if="button_group?.buttons?.length"
				class="mt-6"
				:class="{ 'flex justify-center': layout === 'image_center' }"
				:data-directus="
					setAttr({ collection: 'block_button_group', item: button_group.id, fields: 'buttons', mode: 'modal' })
				"
			>
				<ButtonGroup :buttons="button_group.buttons" />
			</div>
		</div>

		<div
			v-if="image"
			class="relative w-full"
			:class="{
				'md:w-3/4 xl:w-2/3 h-[400px]': layout === 'image_center',
				'md:w-1/2 h-[562px]': layout !== 'image_center',
			}"
			:data-directus="setAttr({ collection: 'block_hero', item: id, fields: 'image', mode: 'modal' })"
		>
			<DirectusImage
				:uuid="image"
				:alt="tagline || headline || 'Hero Image'"
				:fill="true"
				:sizes="layout === 'image_center' ? '100vw' : '(max-width: 768px) 100vw, 50vw'"
				class="object-contain"
			/>
		</div>
	</section>
</template>

// simple-cms/astro/src/components/blocks/Hero.tsx
import Tagline from '@/components/ui/Tagline';
import Headline from '@/components/ui/Headline';
import BaseText from '@/components/ui/Text';
import DirectusImage from '@/components/shared/DirectusImage';
import ButtonGroup from '@/components/blocks/ButtonGroup';
import { cn } from '@/lib/utils';
import { setAttr } from '@directus/visual-editing';

interface HeroProps {
  data: {
    id: string;
    tagline: string;
    headline: string;
    description: string;
    layout: 'image_left' | 'image_center' | 'image_right';
    image: string;
    button_group?: {
      id: string;
      buttons: Array<{
        id: string;
        label: string | null;
        variant: string | null;
        url: string | null;
        type: 'url' | 'page' | 'post';
        pagePermalink?: string | null;
        postSlug?: string | null;
      }>;
    };
  };
}

export default function Hero({ data }: HeroProps) {
  const { id, layout, tagline, headline, description, image, button_group } = data;

  return (
    <section
      className={cn(
        'relative w-full mx-auto flex flex-col gap-6 md:gap-12',
        layout === 'image_center'
          ? 'items-center text-center'
          : layout === 'image_left'
            ? 'md:flex-row-reverse items-center'
            : 'md:flex-row items-center',
      )}
    >
      <div
        className={cn(
          'flex flex-col gap-4 w-full',
          layout === 'image_center' ? 'md:w-3/4 xl:w-2/3 items-center' : 'md:w-1/2 items-start',
        )}
      >
        <Tagline
          tagline={tagline}
          data-directus={setAttr({
            collection: 'block_hero',
            item: id,
            fields: 'tagline',
            mode: 'popover',
          })}
        />
        <Headline
          headline={headline}
          data-directus={setAttr({
            collection: 'block_hero',
            item: id,
            fields: 'headline',
            mode: 'popover',
          })}
        />
        {description && (
          <BaseText
            content={description}
            data-directus={setAttr({
              collection: 'block_hero',
              item: id,
              fields: 'description',
              mode: 'popover',
            })}
          />
        )}
        {button_group && button_group.buttons.length > 0 && (
          <div
            className={cn(layout === 'image_center' && 'flex justify-center', 'mt-6')}
            data-directus={setAttr({
              collection: 'block_button_group',
              item: button_group.id,
              fields: 'buttons',
              mode: 'modal',
            })}
          >
            <ButtonGroup buttons={button_group.buttons} />
          </div>
        )}
      </div>
      {image && (
        <div
          className={cn(
            'relative w-full',
            layout === 'image_center' ? 'md:w-3/4 xl:w-2/3 h-[400px]' : 'md:w-1/2 h-[562px]',
          )}
          data-directus={setAttr({
            collection: 'block_hero',
            item: id,
            fields: ['image', 'layout'],
            mode: 'modal',
          })}
        >
          <DirectusImage
            uuid={image}
            alt={tagline || headline || 'Hero Image'}
            fill
            sizes={layout === 'image_center' ? '100vw' : '(max-width: 768px) 100vw, 50vw'}
            className="object-cover"
          />
        </div>
      )}
    </section>
  );
}
