// simple-cms/nuxt/app/components/block/Pricing.vue
<script setup lang="ts">
interface PricingProps {
	data: {
		tagline?: string;
		headline?: string;
		pricing_cards: Array<{
			id: string;
			title: string;
			description?: string;
			price?: string;
			badge?: string;
			features?: string[];
			button?: {
				id: string;
				label: string | null;
				variant: string | null;
				url: string | null;
			};
			is_highlighted?: boolean;
		}>;
	};
}

const props = defineProps<PricingProps>();

const gridClasses = computed(() => {
	const length = props.data.pricing_cards.length;
	if (length === 1) return 'grid-cols-1';
	if (length % 3 === 0) return 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3';
	return 'grid-cols-1 sm:grid-cols-2';
});
</script>

<template>
	<section>
		<Tagline v-if="data.tagline" :tagline="data.tagline" />
		<Headline v-if="data.headline" :headline="data.headline" />

		<div :class="`grid gap-6 mt-8 ${gridClasses}`">
			<PricingCard v-for="card in data.pricing_cards" :key="card.id" :card="card" />
		</div>
	</section>
</template>

// simple-cms/astro/src/components/blocks/Pricing.tsx
import React from "react";
import Tagline from "../ui/Tagline";
import Headline from "../ui/Headline";
import PricingCard from "./PricingCard";

interface PricingProps {
  data: {
    tagline?: string;
    headline?: string;
    pricing_cards: Array<{
      id: string;
      title: string;
      description?: string;
      price?: string;
      badge?: string;
      features?: string[];
      button?: {
        id: string;
        label: string | null;
        variant: string | null;
        url: string | null;
      };
      is_highlighted?: boolean;
    }>;
  };
}

const Pricing = ({ data }: PricingProps) => {
  const { tagline, headline, pricing_cards } = data;

  if (!pricing_cards || !Array.isArray(pricing_cards)) {
    return null;
  }

  const gridClasses = (() => {
    if (pricing_cards.length === 1) return "grid-cols-1";
    if (pricing_cards.length % 3 === 0)
      return "grid-cols-1 sm:grid-cols-2 lg:grid-cols-3";
    // Default to 2 columns for pricing cards
    return "grid-cols-1 sm:grid-cols-2";
  })();

  return (
    <section>
      {tagline && <Tagline tagline={tagline} />}
      {headline && <Headline headline={headline} />}
      <div className={`grid gap-6 mt-8 ${gridClasses}`}>
        {pricing_cards.map((card) => (
          <PricingCard key={card.id} card={card} />
        ))}
      </div>
    </section>
  );
};

export default Pricing;
