// simple-cms/sveltekit/src/lib/components/blocks/RichText.svelte
<script lang="ts">
	import setAttr from '$lib/directus/visualEditing';
	import { cn } from '$lib/utils';
	import Headline from '../ui/Headline.svelte';
	import Tagline from '../ui/Tagline.svelte';
	import Text from '../ui/Text.svelte';

	interface RichTextProps {
		data: {
			id: string;
			headline?: string;
			content: string;
			alignment?: 'left' | 'center' | 'right';
			tagline?: string;
		};
		className?: string;
	}

	let { data, className }: RichTextProps = $props();

	const { headline, content, alignment = 'left', tagline, id } = $derived(data);
</script>

<div
	class={cn(
		'mx-auto max-w-[600px] space-y-6',
		alignment === 'center' ? 'text-center' : alignment === 'right' ? 'text-right' : 'text-left',
		className
	)}
>
	{#if tagline}
		<Tagline
			{tagline}
			data-directus={setAttr({
				collection: 'block_richtext',
				item: id,
				fields: 'tagline',
				mode: 'popover'
			})}
		/>
	{/if}
	{#if headline}
		<Headline
			{headline}
			data-directus={setAttr({
				collection: 'block_richtext',
				item: id,
				fields: 'headline',
				mode: 'popover'
			})}
		/>
	{/if}
	{#if content}
		<Text
			{content}
			data-directus={setAttr({
				collection: 'block_richtext',
				item: id,
				fields: 'content',
				mode: 'popover'
			})}
		/>
	{/if}
</div>

// simple-cms/astro/src/components/blocks/RichText.tsx
import React from 'react';
import Tagline from '@/components/ui/Tagline';
import Headline from '@/components/ui/Headline';
import Text from '@/components/ui/Text';
import { setAttr } from '@directus/visual-editing';

interface RichTextProps {
  data: {
    id: string;
    tagline?: string;
    headline?: string;
    content?: string;
    alignment?: 'left' | 'center' | 'right';
  };
  className?: string;
}

const RichText = ({ data, className }: RichTextProps) => {
  const { id, tagline, headline, content, alignment = 'left' } = data;

  return (
    <div className={`mx-auto max-w-[600px] space-y-6 text-${alignment} ${className}`}>
      {tagline && (
        <Tagline
          tagline={tagline}
          data-directus={setAttr({
            collection: 'block_richtext',
            item: id,
            fields: 'tagline',
            mode: 'popover',
          })}
        />
      )}
      {headline && (
        <Headline
          headline={headline}
          data-directus={setAttr({
            collection: 'block_richtext',
            item: id,
            fields: 'headline',
            mode: 'popover',
          })}
        />
      )}
      {content && (
        <Text
          content={content}
          data-directus={setAttr({
            collection: 'block_richtext',
            item: id,
            fields: 'content',
            mode: 'popover',
          })}
        />
      )}
    </div>
  );
};

export default RichText;
