// simple-cms/nuxt/app/components/shared/DirectusVisualEditing.vue
<script setup lang="ts">
import { onMounted } from 'vue';

onMounted(async () => {
	const config = useRuntimeConfig().public;

	if (!config.enableVisualEditing) return;

	try {
		const { apply } = await import('@directus/visual-editing');

		await apply({
			directusUrl: config.directusUrl,
			onSaved(updateData) {
				window.dispatchEvent(
					new CustomEvent('directus:update', {
						detail: updateData,
					}),
				);
			},
		});
	} catch (err) {
		console.error('[DirectusVisualEditing] Failed to apply():', err);
	}
});
</script>

<template>
	<slot />
</template>

// simple-cms/astro/src/components/shared/DirectusVisualEditing.tsx
import { useEffect } from 'react';

// This component initializes the Directus visual editing library globally
export default function DirectusVisualEditing() {
  useEffect(() => {
    const loadVisualEditing = async () => {
      try {
        const { apply } = await import('@directus/visual-editing');

        // Initialize Directus visual editing globally
        await apply({
          directusUrl: import.meta.env.PUBLIC_DIRECTUS_URL!,
          onSaved: (updateData) => {
            // Create a custom event to notify components about the update
            const updateEvent = new CustomEvent('directus:update', {
              detail: {
                collection: updateData.collection,
                item: updateData.item,
                payload: updateData.payload,
              },
            });

            // Dispatch the event globally
            window.dispatchEvent(updateEvent);
          },
        });
      } catch (error) {
        console.error('Error initializing Directus Visual Editor:', error);
      }
    };

    loadVisualEditing();
  }, []);

  return null;
}
