// simple-cms/nuxt/app/pages/blog/[slug].vue
<script setup lang="ts">
import { computed } from 'vue';
import { useRoute, useAsyncData, useRuntimeConfig } from 'nuxt/app';
import DirectusImage from '~/components/shared/DirectusImage.vue';
import Separator from '~/components/ui/separator/Separator.vue';

const route = useRoute();
const slug = route.params.slug as string;

const { data: post } = await useAsyncData<Post>(`post-${slug}`, () => $fetch<Post>(`/api/posts/${slug}`));

const { data: relatedPosts } = await useAsyncData<Post[]>(`related-${slug}`, () =>
	$fetch<Post[]>(`/api/posts/${slug}/related`),
);

const { data: author } = await useAsyncData<DirectusUser | null>(`author-${post.value?.author}`, () =>
	$fetch<DirectusUser>(`/api/users/${post.value?.author}`),
);

const postUrl = `${useRuntimeConfig().public.siteUrl}/blog/${slug}`;

const authorName = computed(() => {
	if (!author.value) return '';
	return [author.value.first_name, author.value.last_name].filter(Boolean).join(' ');
});

const authorAvatar = computed(() => {
	if (!author.value?.avatar) return null;
	return typeof author.value.avatar === 'string' ? author.value.avatar : author.value.avatar.id;
});
</script>
<template>
	<div v-if="post">
		<Container class="py-12">
			<div v-if="post.image" class="mb-8 w-full">
				<div class="relative w-full h-[400px] md:h-[500px] overflow-hidden">
					<DirectusImage
						:uuid="post.image as string"
						:alt="post.title || 'post header image'"
						class="object-cover w-full h-full"
						sizes="(max-width: 768px) 100vw, (max-width: 1200px) 100vw, 1200px"
						fill
					/>
				</div>
			</div>

			<Headline :headline="post.title" as="h2" class="!text-accent mb-4" />
			<div class="w-full">
				<Separator class="h-[1px] bg-gray-300 my-8" />
			</div>

			<div class="grid grid-cols-1 lg:grid-cols-[minmax(0,_2fr)_400px] gap-12">
				<main class="text-left">
					<Text :content="post.content || ''" />
				</main>

				<aside class="space-y-6 p-6 rounded-lg max-w-[496px] h-fit bg-background-muted">
					<div v-if="author" class="flex items-center space-x-4">
						<DirectusImage
							v-if="authorAvatar"
							:uuid="authorAvatar"
							:alt="authorName || 'author avatar'"
							class="rounded-full object-cover size-[48px]"
							:width="48"
							:height="48"
						/>
						<div>
							<p v-if="authorName" class="font-bold">{{ authorName }}</p>
						</div>
					</div>

					<p v-if="post.description" class="">{{ post.description }}</p>

					<div class="flex justify-start">
						<ShareDialog :post-url="postUrl" :post-title="post.title" />
					</div>

					<div>
						<Separator class="h-[1px] bg-gray-300 my-4" />
						<h3 class="font-bold mb-4">Related Posts</h3>
						<div class="space-y-4">
							<NuxtLink
								v-for="relatedPost in relatedPosts"
								:key="relatedPost.id"
								:to="`/blog/${relatedPost.slug}`"
								class="flex items-center space-x-4 hover:text-accent group"
							>
								<div v-if="relatedPost.image" class="relative shrink-0 w-[150px] h-[100px] overflow-hidden rounded-lg">
									<DirectusImage
										:uuid="relatedPost.image as string"
										:alt="relatedPost.title || 'related posts'"
										class="object-cover transition-transform duration-300 group-hover:scale-110"
										fill
										sizes="(max-width: 768px) 100px, (max-width: 1024px) 150px, 150px"
									/>
								</div>
								<span class="font-heading">{{ relatedPost.title }}</span>
							</NuxtLink>
						</div>
					</div>
				</aside>
			</div>
		</Container>
	</div>
	<div v-else class="text-center text-xl mt-[20%]">404 - Post Not Found</div>
</template>

// simple-cms/sveltekit/src/routes/blog/[slug]/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { PUBLIC_SITE_URL } from '$env/static/public';
	import DirectusImage from '$lib/components/shared/DirectusImage.svelte';
	import Container from '$lib/components/ui/Container.svelte';
	import Headline from '$lib/components/ui/Headline.svelte';
	import { Separator } from '$lib/components/ui/separator/index.js';
	import type { PageData } from './$types';
	import BaseText from '$lib/components/ui/Text.svelte';
	import ShareDialog from '$lib/components/ui/ShareDialog.svelte';

	let { data }: { data: PageData } = $props();

	let post = $derived(data.post);
	const author = $derived(data.author);
	const authorName = $derived([author?.first_name, author?.last_name].filter(Boolean).join(' '));
	const postUrl = `${PUBLIC_SITE_URL}/blog/${page.params.slug}`;
</script>

<Container class="py-12">
	{#if post?.image}
		<div class="mb-8">
			<div class="relative h-[400px] w-full overflow-hidden rounded-lg">
				<DirectusImage
					uuid={post.image as string}
					alt={post.title || 'post header image'}
					className="object-cover"
					fill
					sizes="(max-width: 768px) 100vw, (max-width: 1200px) 100vw, 1200px"
				/>
			</div>
		</div>
	{/if}
	<Headline as="h2" headline={post.title} class="mb-4 !text-accent" />
	<Separator class="mb-8 border" />

	<div class="grid grid-cols-1 gap-12 lg:grid-cols-[minmax(0,_2fr)_400px]">
		<main class="text-left">
			<BaseText content={post.content || ''} />
		</main>

		<aside class="bg-background-muted h-fit max-w-[496px] space-y-6 rounded-lg p-6">
			{#if author}
				<div class="flex items-center space-x-4">
					{#if author.avatar}
						<DirectusImage
							uuid={author.avatar as string}
							alt={authorName || 'author avatar'}
							className="rounded-full object-cover size-[48px]"
							width={48}
							height={48}
						/>
					{/if}
					<div>
						{#if authorName}
							<p class="font-bold">{authorName}</p>
						{/if}
					</div>
				</div>
			{/if}

			{#if post.description}
				<p class="">{post.description}</p>
			{/if}

			<div class="flex justify-start">
				<ShareDialog {postUrl} postTitle={post.title} />
			</div>

			<div>
				<Separator class="my-4" />
				<h3 class="mb-4 font-bold">Related Posts</h3>
				<div class="space-y-4">
					{#each data.relatedPosts as relatedPost (relatedPost.id)}
						<a
							href={`/blog/${relatedPost.slug}`}
							class="group flex items-center space-x-4 hover:text-accent"
						>
							{#if relatedPost.image}
								<div class="relative h-[100px] w-[150px] shrink-0 overflow-hidden rounded-lg">
									<DirectusImage
										uuid={relatedPost.image as string}
										alt={relatedPost.title || 'related posts'}
										className="object-cover transition-transform duration-300 group-hover:scale-110"
										fill
										sizes="(max-width: 768px) 100px, (max-width: 1024px) 150px, 150px"
									/>
								</div>
							{/if}
							<span class="font-heading">{relatedPost.title}</span>
						</a>
					{/each}
				</div>
			</div>
		</aside>
	</div>
</Container>
