// cms/astro/src/components/forms/fields/RadioGroupField.tsx
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import type { UseFormReturn } from 'react-hook-form';
import React from 'react';

interface RadioGroupFieldProps {
  name: string;
  options: { value: string; text: string }[];
  form: UseFormReturn;
}

const RadioGroupField = ({ name, options, form }: RadioGroupFieldProps) => (
  <RadioGroup
    value={form.watch(name)}
    onValueChange={(value) => form.setValue(name, value)}
    className=""
  >
    {options.map((option) => (
      <div key={option.value} className="flex items-center gap-x-2">
        <RadioGroupItem id={`${name}-${option.value}`} value={option.value} />
        <label htmlFor={`${name}-${option.value}`} className="text-sm">
          {option.text}
        </label>
      </div>
    ))}
  </RadioGroup>
);

export default RadioGroupField;

// simple-cms/nuxt/app/components/forms/fields/RadioGroupField.vue
<script setup lang="ts">
import { computed } from 'vue';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Label } from '@/components/ui/label';

const props = defineProps<{
	modelValue: string;
	name: string;
	options: { value: string; text: string }[];
}>();

const emits = defineEmits(['update:modelValue']);

const localValue = computed({
	get: () => props.modelValue,
	set: (value: string) => emits('update:modelValue', value),
});
</script>

<template>
	<RadioGroup v-model="localValue">
		<div v-for="option in props.options" :key="option.value" class="flex items-center gap-x-2">
			<RadioGroupItem :id="`${props.name}-${option.value}`" :value="option.value" />
			<Label :for="`${props.name}-${option.value}`" class="text-sm">
				{{ option.text }}
			</Label>
		</div>
	</RadioGroup>
</template>
