// cms/astro/src/components/forms/fields/CheckboxGroupField.tsx
import { Checkbox } from '@/components/ui/checkbox';
import type { UseFormReturn } from 'react-hook-form';

interface CheckboxGroupFieldProps {
  name: string;
  options: { value: string; text: string }[];
  form: UseFormReturn<Record<string, string[]>>;
}

const CheckboxGroupField = ({
  name,
  options,
  form,
}: CheckboxGroupFieldProps) => {
  const currentValues = form.watch(name) || [];

  const toggleValue = (value: string, checked?: boolean) => {
    const updatedValues = checked
      ? [...currentValues, value]
      : currentValues.filter((v) => v !== value);

    form.setValue(name, updatedValues);
  };

  return (
    <div>
      {options.map((option) => (
        <div key={option.value} className="flex items-center gap-x-2">
          <Checkbox
            id={`${name}-${option.value}`}
            checked={currentValues.includes(option.value)}
            onCheckedChange={(checked) => toggleValue(option.value, !!checked)}
          />
          <label htmlFor={`${name}-${option.value}`} className="text-sm">
            {option.text}
          </label>
        </div>
      ))}
    </div>
  );
};

export default CheckboxGroupField;

// simple-cms/sveltekit/src/lib/components/forms/fields/CheckBoxGroupField.svelte
<script lang="ts">
	import { Checkbox } from '$lib/components/ui/checkbox';

	interface CheckboxGroupFieldProps {
		name: string;
		options: { value: string; text: string }[];
		// form: UseFormReturn<any>;
		form?: any;
	}

	const { name = 'unknown', options, form }: CheckboxGroupFieldProps = $props();
</script>

<div>
	{#each options as option (option.value)}
		<div class="flex items-center gap-x-2">
			<Checkbox id={`${name}-${option.value}`} />
			<!-- checked={currentValues.includes(option.value)}
				onCheckedChange={(checked) => toggleValue(option.value, !!checked)} -->
			<label for={`${name}-${option.value}`} class="text-sm">
				{option.text}
			</label>
		</div>
	{/each}
</div>
