// simple-cms/astro/src/components/forms/fields/FileUploadField.tsx
import { Input } from "@/components/ui/input";
import type { UseFormReturn } from "react-hook-form";
import React from "react";

interface FileUploadFieldProps {
  name: string;
  form: UseFormReturn;
}

const FileUploadField = ({ name, form }: FileUploadFieldProps) => {
  return (
    <Input
      type="file"
      id={name}
      onChange={(e) => {
        const file = e.target.files?.[0];
        form.setValue(name, file);
      }}
    />
  );
};

export default FileUploadField;

// simple-cms/sveltekit/src/lib/components/forms/fields/FileUploadField.svelte
<script lang="ts">
	import { Input } from '$lib/components/ui/command';

	interface FileUploadFieldProps {
		name: string;
		form: any;
	}

	const { name, form }: FileUploadFieldProps = $props();

	const { form: formData } = form;

	const onFileChange = (e: Event) => {
		const file = (e.target as HTMLInputElement).files?.[0];
		formData[name] = file;
	};
</script>

<Input type="file" id={name} onchange={onFileChange} />
