// cms/sveltekit/src/lib/components/ui/SearchModal.svelte
<script lang="ts">
	import { Button, buttonVariants } from '$lib/components/ui/button/index.js';

	import { Search } from '@lucide/svelte';
	import * as Command from '$lib/components/ui/command/index.js';

	import { debounce } from '$lib/utils';
	import Badge from './badge/badge.svelte';
	import { goto } from '$app/navigation';

	let open = $state(false);
	let search = $state('');
	let searched = $state(false);
	let loading = $state(false);
	let results = $state<SearchResult[]>([]);

	type SearchResult = {
		id: string;
		title: string;
		description: string;
		type: string;
		link: string;
	};

	const handleKeydown = (e: KeyboardEvent) => {
		if (e.key === 'k' && (e.metaKey || e.ctrlKey)) {
			e.preventDefault();
			open = !open;
		}
	};

	$effect(() => {
		if (!open) {
			// results = [];
			searched = false;
			loading = false;
		}
	});

	const fetchResults = async (search: string) => {
		if (search.length < 3 || !open) {
			results = [];
			// searched = false;
			return;
		}

		loading = true;
		// searched = true;

		try {
			const res = await fetch(`/api/search?search=${encodeURIComponent(search)}`);
			if (!res.ok) throw new Error('Failed to fetch results');
			const data: SearchResult[] = await res.json();
			results = data.filter((r) => r.link);
		} catch (error) {
			console.error('Error fetching search results:', error);
			results = [];
		} finally {
			loading = false;
		}
	};
	const debouncedFetchResults = debounce(fetchResults, 300);

	$effect(() => {
		debouncedFetchResults(search);
	});

	const handleSelect = (result: SearchResult) => {
		goto(result.link);
		open = false;
	};
</script>

<svelte:document onkeydown={handleKeydown} />

<div class="max-w-full sm:max-w-[540px]">
	<Button variant="ghost" size="icon" aria-label="Search" onclick={() => (open = true)}>
		<Search class="size-5" />
	</Button>

	<Command.Dialog bind:open shouldFilter={false}>
		<Command.Input
			placeholder="Type a command or search..."
			bind:value={search}
			class="m-2 p-4 text-base leading-normal focus:outline-hidden"
		/>
		<Command.List>
			{#if !loading && !searched}
				<Command.Empty>No results found.</Command.Empty>
			{/if}

			{#if loading}
				<Command.Empty class="py-2 text-center text-sm">Loading...</Command.Empty>
			{/if}

			{#if !loading && searched && results.length === 0}
				<Command.Empty class="py-2 text-center text-sm">No results found.</Command.Empty>
			{/if}

			{#if results.length > 0}
				<Command.Group heading="Search Results">
					{#each results as result}
						<Command.Item
							class="flex items-start gap-4 px-2 py-3"
							onSelect={() => handleSelect(result)}
						>
							<Badge variant="default">{result.type}</Badge>
							<div class="ml-2 w-full">
								<p class="text-base font-medium">{result.title}</p>
								<p class="mt-1 line-clamp-2 text-sm">{result.description}</p>
							</div>
						</Command.Item>
					{/each}
				</Command.Group>
			{/if}
		</Command.List>
	</Command.Dialog>
</div>

// simple-cms/nextjs/src/components/ui/SearchModal.tsx
'use client';

import { useEffect, useState } from 'react';
import {
	CommandDialog,
	CommandEmpty,
	CommandGroup,
	CommandInput,
	CommandItem,
	CommandList,
} from '@/components/ui/command';
import { Button } from '@/components/ui/button';
import { Search } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { debounce } from '@/lib/utils';
import { DialogDescription, DialogTitle } from './dialog';
import { useRouter } from 'next/navigation';

type SearchResult = {
	id: string;
	title: string;
	description: string;
	type: string;
	link: string;
};

export default function SearchModal() {
	const [open, setOpen] = useState(false);
	const [results, setResults] = useState<SearchResult[]>([]);
	const [loading, setLoading] = useState(false);
	const [searched, setSearched] = useState(false);

	const router = useRouter();

	useEffect(() => {
		const onKeyDown = (e: KeyboardEvent) => {
			if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
				e.preventDefault();
				setOpen((prev) => !prev);
			}
		};
		document.addEventListener('keydown', onKeyDown);

		return () => document.removeEventListener('keydown', onKeyDown);
	}, []);

	useEffect(() => {
		if (!open) {
			setResults([]);
			setSearched(false);
			setLoading(false);
		}
	}, [open]);

	const fetchResults = async (search: string) => {
		if (search.length < 3) {
			setResults([]);
			setSearched(false);

			return;
		}

		setLoading(true);
		setSearched(true);

		try {
			const res = await fetch(`/api/search?search=${encodeURIComponent(search)}`);
			if (!res.ok) throw new Error('Failed to fetch results');
			const data: SearchResult[] = await res.json();
			setResults(data.filter((r) => r.link));
		} catch (error) {
			console.error('Error fetching search results:', error);
			setResults([]);
		} finally {
			setLoading(false);
		}
	};

	const debouncedFetchResults = debounce(fetchResults, 300);

	return (
		<div className="sm:max-w-[540px] max-w-full">
			<Button variant="ghost" size="icon" onClick={() => setOpen(true)} aria-label="Search">
				<Search className="size-5" />
			</Button>

			<CommandDialog open={open} onOpenChange={setOpen}>
				<DialogTitle className="p-2 sr-only">Search</DialogTitle>
				<DialogDescription className="px-2 sr-only">Search for pages or posts</DialogDescription>

				<CommandInput
					placeholder="Search for pages or posts"
					onValueChange={(value) => debouncedFetchResults(value)}
					className="m-2 focus:outline-none p-2"
				/>

				<CommandList className="p-2 text-foreground max-h-[500px] overflow-auto">
					{!loading && !searched && (
						<CommandEmpty className="py-2 text-sm text-center">Enter a search term above to see results</CommandEmpty>
					)}
					{loading && <CommandEmpty className="py-2 text-sm text-center">Loading...</CommandEmpty>}
					{!loading && searched && results.length === 0 && (
						<CommandEmpty className="py-2 text-sm text-center">No results found</CommandEmpty>
					)}
					{!loading && results.length > 0 && (
						<CommandGroup heading="Search Results" className="pt-2" forceMount>
							{results.map((result) => (
								<CommandItem
									key={result.id}
									className="flex items-start gap-4 px-2 py-3"
									onSelect={() => {
										router.push(result.link);
										setOpen(false);
									}}
								>
									<Badge variant="default">{result.type}</Badge>
									<div className="ml-2 w-full">
										<p className="font-medium text-base">{result.title}</p>
										{result.description && <p className="text-sm mt-1 line-clamp-2">{result.description}</p>}
									</div>
								</CommandItem>
							))}
						</CommandGroup>
					)}
				</CommandList>
			</CommandDialog>
		</div>
	);
}
