// simple-cms/sveltekit/src/lib/components/ui/Headline.svelte
<script lang="ts">
	interface Props {
		headline?: string | null;
		as?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'span' | 'div';
		[key: string]: any;
	}

	let { headline, as = 'p', ...props }: Props = $props();
</script>

{#if headline}
	<as
		class="font-heading font-normal text-foreground {props.class}
         lg:text-headline text-4xl md:text-5xl">{headline}</as
	>
{/if}

// simple-cms/astro/src/components/ui/Headline.tsx
import React from "react";

interface HeadlineProps {
  headline?: string | null;
  className?: string;
  as?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "p" | "span" | "div";
}

const Headline = ({
  headline,
  className = "",
  as: Component = "p",
}: HeadlineProps) => {
  if (!headline) return null;

  return (
    <Component
      className={`font-heading text-foreground font-normal text-4xl md:text-5xl lg:text-headline ${className}`}
    >
      {headline}
    </Component>
  );
};

export default Headline;
