// simple-cms/nuxt/app/components/forms/fields/CheckboxField.vue
<script setup lang="ts">
import { computed } from 'vue';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';

const props = defineProps<{
	modelValue: boolean;
	name: string;
	label: string;
}>();

const emits = defineEmits(['update:modelValue']);

const localValue = computed({
	get: () => props.modelValue,
	set: (value: boolean) => emits('update:modelValue', value),
});
</script>

<template>
	<div class="flex items-center gap-x-2">
		<Checkbox :id="props.name" v-model:checked="localValue" />
		<Label :for="props.name" class="text-sm">{{ props.label }}</Label>
	</div>
</template>

// simple-cms/astro/src/components/forms/fields/CheckboxField.tsx
import { Checkbox } from "@/components/ui/checkbox";
import React from "react";
import type { UseFormReturn } from "react-hook-form";

interface CheckboxFieldProps {
  name: string;
  label: string;
  form: UseFormReturn<any>;
}

const CheckboxField = ({ name, label, form }: CheckboxFieldProps) => (
  <div className="flex items-center gap-x-2">
    <Checkbox
      id={name}
      checked={form.watch(name)}
      onCheckedChange={(checked) => form.setValue(name, checked)}
    />
    <label htmlFor={name} className="text-sm">
      {label}
    </label>
  </div>
);

export default CheckboxField;
