// simple-cms/nuxt/app/components/forms/fields/CheckboxGroupField.vue
<script setup lang="ts">
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';

const props = defineProps<{
	modelValue: string[];
	name: string;
	options: { value: string; text: string }[];
}>();

const emits = defineEmits(['update:modelValue']);

const isChecked = (value: string) => props.modelValue.includes(value);

const toggleValue = (value: string, checked: boolean) => {
	let updatedValues = [...props.modelValue];

	if (checked) {
		updatedValues.push(value);
	} else {
		updatedValues = updatedValues.filter((v) => v !== value);
	}

	emits('update:modelValue', updatedValues);
};
</script>

<template>
	<div>
		<div v-for="option in props.options" :key="option.value" class="flex items-center gap-x-2">
			<Checkbox
				:id="`${props.name}-${option.value}`"
				:checked="isChecked(option.value)"
				@update:checked="(checked) => toggleValue(option.value, checked)"
			/>
			<Label :for="`${props.name}-${option.value}`" class="text-sm">
				{{ option.text }}
			</Label>
		</div>
	</div>
</template>

// simple-cms/astro/src/components/forms/fields/CheckboxGroupField.tsx
import { Checkbox } from "@/components/ui/checkbox";
import type { UseFormReturn } from "react-hook-form";
import React from "react";

interface CheckboxGroupFieldProps {
  name: string;
  options: { value: string; text: string }[];
  form: UseFormReturn<any>;
}

const CheckboxGroupField = ({
  name,
  options,
  form,
}: CheckboxGroupFieldProps) => {
  const currentValues = form.watch(name) || [];

  const toggleValue = (value: string, checked?: boolean) => {
    const updatedValues = checked
      ? [...currentValues, value]
      : currentValues.filter((v: string) => v !== value);
    form.setValue(name, updatedValues);
  };

  return (
    <div>
      {options.map((option) => (
        <div key={option.value} className="flex items-center gap-x-2">
          <Checkbox
            id={`${name}-${option.value}`}
            checked={currentValues.includes(option.value)}
            onCheckedChange={(checked) => toggleValue(option.value, !!checked)}
          />
          <label htmlFor={`${name}-${option.value}`} className="text-sm">
            {option.text}
          </label>
        </div>
      ))}
    </div>
  );
};

export default CheckboxGroupField;
