// simple-cms/nuxt/app/components/forms/fields/SelectField.vue
<script setup lang="ts">
import { computed } from 'vue';
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

const props = defineProps<{
	modelValue: string;
	name: string;
	options: { value: string; text: string }[];
	placeholder?: string;
}>();

const emits = defineEmits(['update:modelValue']);

const localValue = computed({
	get: () => props.modelValue,
	set: (value: string) => emits('update:modelValue', value),
});
</script>

<template>
	<Select v-model="localValue">
		<SelectTrigger :id="props.name">
			<SelectValue :placeholder="props.placeholder || 'Select an option'" />
		</SelectTrigger>
		<SelectContent>
			<SelectGroup>
				<SelectItem v-for="option in props.options" :key="option.value" :value="option.value">
					{{ option.text }}
				</SelectItem>
			</SelectGroup>
		</SelectContent>
	</Select>
</template>

// cms/astro/src/components/forms/fields/SelectField.tsx
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from '@/components/ui/select';
import type { UseFormReturn } from 'react-hook-form';

interface SelectFieldProps {
  name: string;
  options: { value: string; text: string }[];
  placeholder?: string | null;
  form: UseFormReturn;
}

const SelectField = ({
  name,
  options,
  placeholder,
  form,
}: SelectFieldProps) => {
  return (
    <Select
      onValueChange={(value) => form.setValue(name, value)}
      value={form.getValues(name)}
    >
      <SelectTrigger>
        <SelectValue placeholder={placeholder || 'Select an option'} />
      </SelectTrigger>
      <SelectContent>
        {options.map((option) => (
          <SelectItem key={option.value} value={option.value}>
            {option.text}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
};

export default SelectField;
