// simple-cms/nextjs/src/components/blocks/BaseBlock.tsx
import RichText from '@/components/blocks/RichText';
import Hero from '@/components/blocks/Hero';
import Gallery from '@/components/blocks/Gallery';
import Pricing from '@/components/blocks/Pricing';
import Posts from '@/components/blocks/Posts';
import Form from '@/components/blocks/Form';

interface BaseBlockProps {
	block: {
		collection: string;
		item: any;
	};
}

const BaseBlock = ({ block }: BaseBlockProps) => {
	const components: Record<string, React.ElementType> = {
		block_hero: Hero,
		block_richtext: RichText,
		block_gallery: Gallery,
		block_pricing: Pricing,
		block_posts: Posts,
		block_form: Form,
	};

	const Component = components[block.collection];

	if (!Component) {
		return null;
	}

	return <Component data={block.item} />;
};

export default BaseBlock;

// simple-cms/nuxt/app/components/base/BaseBlock.vue
<script setup lang="ts">
import { computed } from 'vue';
import Hero from '~/components/block/Hero.vue';
import RichText from '~/components/block/RichText.vue';
import Gallery from '../block/Gallery.vue';
import Pricing from '../block/Pricing.vue';
import Posts from '../block/Posts.vue';
import Form from '../block/Form.vue';

interface BaseBlockProps {
	block: {
		collection: string;
		item: any;
		id: string;
	};
}

const props = defineProps<BaseBlockProps>();

const components: Record<string, any> = {
	block_hero: Hero,
	block_richtext: RichText,
	block_gallery: Gallery,
	block_pricing: Pricing,
	block_posts: Posts,
	block_form: Form,
};

const Component = computed(() => components[props.block.collection] || null);
const blockData = computed(() => props.block.item);
</script>
<template>
	<component :is="Component" v-if="Component" :id="`block-${block.id}`" :data="blockData" />
</template>
