// cms/astro/src/components/ui/Container.tsx
import type { PropsWithChildren } from 'react';
import { cn } from '@/lib/utils';

type SemanticElement =
  | 'div'
  | 'section'
  | 'main'
  | 'article'
  | 'aside'
  | 'nav'
  | 'header'
  | 'footer'
  | 'form';
interface ContainerProps extends PropsWithChildren {
  className?: string;
  as?: SemanticElement;
  role?: string;
}

export default function Container({
  children = null,
  className = '',
  as: Component = 'div',
  role,
}: ContainerProps) {
  if (!children) return null;

  return (
    <Component
      className={cn('max-w-7xl mx-auto px-4 sm:px-6 lg:px-16', className)}
      role={role}
    >
      {children}
    </Component>
  );
}

// simple-cms/nuxt/app/components/base/Container.vue
<script setup lang="ts">
export interface ContainerProps {
	as?: 'div' | 'section' | 'main' | 'article' | 'aside' | 'nav' | 'header' | 'footer' | 'form';
	className?: string;
	role?: string;
}

const props = withDefaults(defineProps<ContainerProps>(), {
	as: 'div',
	className: '',
	role: undefined,
});
</script>

<template>
	<component :is="as" :class="['max-w-7xl mx-auto px-4 sm:px-6 lg:px-16', className]" :role="role">
		<slot />
	</component>
</template>
