// simple-cms/nuxt/app/components/base/ButtonGroup.vue
<script setup lang="ts">
import { cn } from '@@/shared/utils';
import Button, { type ButtonProps } from './Button.vue';

export interface ButtonGroupProps {
	buttons: Array<ButtonProps>;
	className?: string;
}

const props = defineProps<ButtonGroupProps>();

const containerClasses = computed(() => cn('flex gap-4', props.className));
</script>
<template>
	<div v-if="buttons?.length" :class="containerClasses">
		<Button v-for="(button, index) in buttons" :key="index" v-bind="button" />
	</div>
</template>

// simple-cms/nextjs/src/components/blocks/ButtonGroup.tsx
import Button, { ButtonProps } from './Button';
import { cn } from '@/lib/utils/cn';

export interface ButtonGroupProps {
	buttons: Array<ButtonProps>;
	className?: string;
}

const ButtonGroup = ({ buttons, className }: ButtonGroupProps) => {
	if (!buttons || !buttons.length) return null;

	const containerClasses = cn('flex gap-4', className);

	return (
		<div className={containerClasses}>
			{buttons.map((button, index) => (
				<Button key={index} {...button} />
			))}
		</div>
	);
};

export default ButtonGroup;
