// simple-cms/nuxt/app/components/base/ThemeToggle.vue
<script setup lang="ts">
const props = defineProps({
	className: {
		type: String,
		default: '',
	},
});

const colorMode = useColorMode();
const isDark = computed(
	() => colorMode.preference === 'dark' || (colorMode.preference === 'system' && colorMode.value === 'dark'),
);

const toggleTheme = () => {
	colorMode.preference = isDark.value ? 'light' : 'dark';
};
</script>

<template>
	<button
		aria-label="Toggle Dark Mode"
		:class="[
			'p-1 rounded-full border border-gray-300 dark:border-gray-600',
			'bg-gray-100 dark:bg-gray-800 transition-colors',
			className,
		]"
		@click="toggleTheme"
	>
		<svg
			v-if="isDark"
			xmlns="http://www.w3.org/2000/svg"
			class="size-5"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			stroke-width="2"
			stroke-linecap="round"
			stroke-linejoin="round"
		>
			<path d="M12 3h.393a7.5 7.5 0 0 0 7.92 12.446A9 9 0 1 1 12 2.992z" />
		</svg>
		<svg
			v-else
			xmlns="http://www.w3.org/2000/svg"
			class="size-5"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			stroke-width="2"
			stroke-linecap="round"
			stroke-linejoin="round"
		>
			<path
				d="M8 12a4 4 0 1 0 8 0a4 4 0 1 0-8 0m-5 0h1m8-9v1m8 8h1m-9 8v1M5.6 5.6l.7.7m12.1-.7l-.7.7m0 11.4l.7.7m-12.1-.7l-.7.7"
			/>
		</svg>
	</button>
</template>

// cms/astro/src/components/ui/ThemeToggle.tsx
'use client';

import { useState, useEffect } from 'react';
import clsx from 'clsx';
import React from 'react';

interface ThemeToggleProps {
  className?: string;
}

export default function ThemeToggle({ className }: ThemeToggleProps) {
  const [theme, setTheme] = useState<'light' | 'dark'>('light');

  useEffect(() => {
    const storedTheme = localStorage.getItem('theme');
    const prefersDark = window.matchMedia(
      '(prefers-color-scheme: dark)',
    ).matches;
    if (storedTheme === 'dark' || (!storedTheme && prefersDark)) {
      setTheme('dark');
      document.documentElement.classList.add('dark');
    } else {
      setTheme('light');
      document.documentElement.classList.remove('dark');
    }
  }, []);

  const toggleTheme = () => {
    if (theme === 'dark') {
      setTheme('light');
      document.documentElement.classList.remove('dark');
      localStorage.setItem('theme', 'light');
    } else {
      setTheme('dark');
      document.documentElement.classList.add('dark');
      localStorage.setItem('theme', 'dark');
    }
  };

  const isDark = theme === 'dark';

  return (
    <button
      aria-label="Toggle Dark Mode"
      onClick={toggleTheme}
      className={clsx(
        'p-1 rounded-full border border-gray-300 dark:border-gray-600 bg-gray-100 dark:bg-gray-800 transition-colors',
        className,
      )}
    >
      {isDark ? (
        <svg
          xmlns="http://www.w3.org/2000/svg"
          className="size-5"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth={2}
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <path d="M12 3h.393a7.5 7.5 0 0 0 7.92 12.446A9 9 0 1 1 12 2.992z" />
        </svg>
      ) : (
        <svg
          xmlns="http://www.w3.org/2000/svg"
          className="size-5"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth={2}
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <path d="M8 12a4 4 0 1 0 8 0a4 4 0 1 0-8 0m-5 0h1m8-9v1m8 8h1m-9 8v1M5.6 5.6l.7.7m12.1-.7l-.7.7m0 11.4l.7.7m-12.1-.7l-.7.7" />
        </svg>
      )}
    </button>
  );
}
