// cms/nuxt/app/components/block/Pricing.vue
<script setup lang="ts">
interface PricingProps {
	data: {
		id?: string;
		tagline?: string;
		headline?: string;
		pricing_cards: Array<{
			id: string;
			title: string;
			description?: string;
			price?: string;
			badge?: string;
			features?: string[];
			button?: {
				id: string;
				label: string | null;
				variant: string | null;
				url: string | null;
			};
			is_highlighted?: boolean;
		}>;
	};
}
import { setBlockAttr } from '~/utils/visualEditing';

defineProps<PricingProps>();
</script>

<template>
	<section>
		<Tagline
			v-if="data.tagline"
			:tagline="data.tagline"
			:data-directus="
				setBlockAttr({
					blockCollection: 'block_pricing',
					blockItemId: data.id,
					fields: 'tagline',
					mode: 'popover',
				})
			"
		/>
		<Headline
			v-if="data.headline"
			:headline="data.headline"
			:data-directus="
				setBlockAttr({
					blockCollection: 'block_pricing',
					blockItemId: data.id,
					fields: 'headline',
					mode: 'popover',
				})
			"
		/>

		<div
			class="grid gap-6 mt-8"
			:class="{
				'grid-cols-1': data.pricing_cards.length === 1,
				'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3': data.pricing_cards.length % 3 === 0,
				'grid-cols-1 sm:grid-cols-2': data.pricing_cards.length % 3 !== 0 && data.pricing_cards.length !== 1,
			}"
			:data-directus="
				setBlockAttr({
					blockCollection: 'block_pricing',
					blockItemId: data.id,
					fields: ['pricing_cards'],
					mode: 'modal',
				})
			"
		>
			<PricingCard v-for="card in data.pricing_cards" :key="card.id" :card="card" />
		</div>
	</section>
</template>

// cms-i18n/nextjs/src/components/blocks/Pricing.tsx
'use client';

import Tagline from '@/components/ui/Tagline';
import Headline from '@/components/ui/Headline';
import PricingCard from '@/components/blocks/PricingCard';
import { setBlockAttr } from '@/lib/directus/visualEditing';

interface PricingCardType {
	id: string;
	title: string;
	description?: string;
	price?: string;
	badge?: string;
	features?: string[];
	button?: {
		id: string;
		label: string | null;
		variant: string | null;
		url: string | null;
	};
	is_highlighted?: boolean;
}

interface PricingData {
	id: string;
	tagline?: string;
	headline?: string;
	pricing_cards: PricingCardType[];
}

interface PricingProps {
	data: PricingData;
}

const Pricing = ({ data }: PricingProps) => {
	const { id, tagline, headline, pricing_cards } = data;

	if (!pricing_cards || !Array.isArray(pricing_cards)) {
		return null;
	}

	const gridClasses = (() => {
		if (pricing_cards.length === 1) return 'grid-cols-1';
		if (pricing_cards.length % 3 === 0) return 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3';

		return 'grid-cols-1 sm:grid-cols-2';
	})();

	return (
		<section>
			{tagline && (
				<Tagline
					tagline={tagline}
					data-directus={setBlockAttr({
						blockCollection: 'block_pricing',
						blockItemId: id,
						fields: 'tagline',
						mode: 'popover',
					})}
				/>
			)}
			{headline && (
				<Headline
					headline={headline}
					data-directus={setBlockAttr({
						blockCollection: 'block_pricing',
						blockItemId: id,
						fields: 'headline',
						mode: 'popover',
					})}
				/>
			)}
			<div
				className={`grid gap-6 mt-8 ${gridClasses}`}
				data-directus={setBlockAttr({
					blockCollection: 'block_pricing',
					blockItemId: id,
					fields: ['pricing_cards'],
					mode: 'modal',
				})}
			>
				{pricing_cards.map((card) => (
					<PricingCard key={card.id} card={card} />
				))}
			</div>
		</section>
	);
};

export default Pricing;
